// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/disconnected.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

#include "ax25sdl.h"

static const ActionStep data_link_disconnected_t01_dl_disconnect_request_actions[] = {
    { .verb = "DL-DISCONNECT Confirm", .kind = AX25SDL_KIND_SIGNAL_UPPER },
};

static const ActionStep data_link_disconnected_t02_dl_unit_data_request_actions[] = {
    { .verb = "UI Command", .kind = AX25SDL_KIND_SIGNAL_LOWER },
};

static const ActionStep data_link_disconnected_t03_dl_connect_request_actions[] = {
    { .verb = "SRT := Initial Default", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "T1V := 2 * SRT", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE },
    { .verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING },
};

static const ActionStep data_link_disconnected_t05_all_other_commands_actions[] = {
    { .verb = "F := P", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DM", .kind = AX25SDL_KIND_SIGNAL_LOWER },
};

static const ActionStep data_link_disconnected_t06_all_other_primitives__from_lower_layer_actions[] = {
    { .verb = "Discard Primitive", .kind = AX25SDL_KIND_PROCESSING },
};

static const ActionStep data_link_disconnected_t07_control_field_error_actions[] = {
    { .verb = "DL-ERROR Indication (L)", .kind = AX25SDL_KIND_SIGNAL_UPPER },
};

static const ActionStep data_link_disconnected_t08_info_not_permitted_in_frame_actions[] = {
    { .verb = "DL-ERROR Indication (M)", .kind = AX25SDL_KIND_SIGNAL_UPPER },
};

static const ActionStep data_link_disconnected_t09_u_or_s_frame_length_error_actions[] = {
    { .verb = "DL-ERROR Indication (N)", .kind = AX25SDL_KIND_SIGNAL_UPPER },
};

static const ActionStep data_link_disconnected_t10_ua_received_actions[] = {
    { .verb = "DL-ERROR Indication (C,D)", .kind = AX25SDL_KIND_SIGNAL_UPPER },
};

static const ActionStep data_link_disconnected_t11_ui_received_no_actions[] = {
    { .verb = "UI Check", .kind = AX25SDL_KIND_SUBROUTINE },
};

static const ActionStep data_link_disconnected_t11_ui_received_yes_actions[] = {
    { .verb = "UI Check", .kind = AX25SDL_KIND_SUBROUTINE },
    { .verb = "F := 1", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DM", .kind = AX25SDL_KIND_SIGNAL_LOWER },
};

static const ActionStep data_link_disconnected_t12_disc_received_actions[] = {
    { .verb = "F := P", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DM", .kind = AX25SDL_KIND_SIGNAL_LOWER },
};

static const ActionStep data_link_disconnected_t13_sabm_received_no_actions[] = {
    { .verb = "F := P", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DM", .kind = AX25SDL_KIND_SIGNAL_LOWER },
};

static const ActionStep data_link_disconnected_t13_sabm_received_yes_actions[] = {
    { .verb = "F := P", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "set_version_2_0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER },
    { .verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_SUBROUTINE },
    { .verb = "V(s) := 0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "V(a) := 0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "V(r) := 0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DL Connect Indication", .kind = AX25SDL_KIND_SIGNAL_UPPER },
    { .verb = "SRT := Initial Default", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "T1V := 2 * SRT", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING },
};

static const ActionStep data_link_disconnected_t14_sabme_received_no_actions[] = {
    { .verb = "F := P", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DM", .kind = AX25SDL_KIND_SIGNAL_LOWER },
};

static const ActionStep data_link_disconnected_t14_sabme_received_yes_actions[] = {
    { .verb = "F := P", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "Set Version 2.2", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER },
    { .verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_SUBROUTINE },
    { .verb = "V(s) := 0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "V(a) := 0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "V(r) := 0", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "DL Connect Indication", .kind = AX25SDL_KIND_SIGNAL_UPPER },
    { .verb = "SRT := Initial Default", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "T1V := 2 * SRT", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING },
    { .verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING },
};

static const TransitionSpec data_link_disconnected_transitions[] = {
    {
        .id = "t01_dl_disconnect_request",
        .from = "Disconnected",
        .on = "DL_DISCONNECT_request",
        .guard = "",
        .actions = data_link_disconnected_t01_dl_disconnect_request_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_dl_unit_data_request",
        .from = "Disconnected",
        .on = "DL_UNIT_DATA_request",
        .guard = "",
        .actions = data_link_disconnected_t02_dl_unit_data_request_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_dl_connect_request",
        .from = "Disconnected",
        .on = "DL_CONNECT_request",
        .guard = "",
        .actions = data_link_disconnected_t03_dl_connect_request_actions,
        .actions_len = 4,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t04_all_other_primitives__from_upper_layer",
        .from = "Disconnected",
        .on = "all_other_primitives__from_upper_layer",
        .guard = "",
        .actions = NULL,
        .actions_len = 0,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t05_all_other_commands",
        .from = "Disconnected",
        .on = "all_other_commands",
        .guard = "",
        .actions = data_link_disconnected_t05_all_other_commands_actions,
        .actions_len = 2,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t06_all_other_primitives__from_lower_layer",
        .from = "Disconnected",
        .on = "all_other_primitives__from_lower_layer",
        .guard = "",
        .actions = data_link_disconnected_t06_all_other_primitives__from_lower_layer_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t07_control_field_error",
        .from = "Disconnected",
        .on = "control_field_error",
        .guard = "",
        .actions = data_link_disconnected_t07_control_field_error_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t08_info_not_permitted_in_frame",
        .from = "Disconnected",
        .on = "info_not_permitted_in_frame",
        .guard = "",
        .actions = data_link_disconnected_t08_info_not_permitted_in_frame_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t09_u_or_s_frame_length_error",
        .from = "Disconnected",
        .on = "u_or_s_frame_length_error",
        .guard = "",
        .actions = data_link_disconnected_t09_u_or_s_frame_length_error_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t10_ua_received",
        .from = "Disconnected",
        .on = "UA_received",
        .guard = "",
        .actions = data_link_disconnected_t10_ua_received_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t11_ui_received_no",
        .from = "Disconnected",
        .on = "UI_received",
        .guard = "not P_eq_1",
        .actions = data_link_disconnected_t11_ui_received_no_actions,
        .actions_len = 1,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t11_ui_received_yes",
        .from = "Disconnected",
        .on = "UI_received",
        .guard = "P_eq_1",
        .actions = data_link_disconnected_t11_ui_received_yes_actions,
        .actions_len = 3,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t12_disc_received",
        .from = "Disconnected",
        .on = "DISC_received",
        .guard = "",
        .actions = data_link_disconnected_t12_disc_received_actions,
        .actions_len = 2,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t13_sabm_received_no",
        .from = "Disconnected",
        .on = "SABM_received",
        .guard = "not able_to_establish",
        .actions = data_link_disconnected_t13_sabm_received_no_actions,
        .actions_len = 2,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t13_sabm_received_yes",
        .from = "Disconnected",
        .on = "SABM_received",
        .guard = "able_to_establish",
        .actions = data_link_disconnected_t13_sabm_received_yes_actions,
        .actions_len = 12,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t14_sabme_received_no",
        .from = "Disconnected",
        .on = "SABME_received",
        .guard = "not able_to_establish",
        .actions = data_link_disconnected_t14_sabme_received_no_actions,
        .actions_len = 2,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t14_sabme_received_yes",
        .from = "Disconnected",
        .on = "SABME_received",
        .guard = "able_to_establish",
        .actions = data_link_disconnected_t14_sabme_received_yes_actions,
        .actions_len = 12,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

const StatePage data_link_disconnected = {
    .machine = "data_link",
    .state = "Disconnected",
    .source = { .spec = "ax.25.2.2.4_Oct_25", .figure = "figc4.1", .url = "" },
    .transitions = data_link_disconnected_transitions,
    .transitions_len = 17,
};
