// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/awaiting_release.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

import "testing"

func TestDataLinkAwaitingRelease_SourceFigure(t *testing.T) {
	if got := DataLinkAwaitingRelease.Source.Figure; got != "figc4.3" {
		t.Errorf("Source.Figure = %q, want figc4.3", got)
	}
}

func TestDataLinkAwaitingRelease_TransitionsArePresent(t *testing.T) {
	if got := len(DataLinkAwaitingRelease.Transitions); got != 20 {
		t.Errorf("len(Transitions) = %d, want 20", got)
	}
}

func TestDataLinkAwaitingRelease_t01_dl_disconnect_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t01_dl_disconnect_request" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t01_dl_disconnect_request not found")
	}
	if tx.On != "DL_DISCONNECT_request" {
		t.Errorf("On = %q, want DL_DISCONNECT_request", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "Expedited DM" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "Expedited DM")
	}
	if tx.Actions[0].Kind != SignalLower {
		t.Errorf("Actions[0].Kind = %v, want SignalLower", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t02_t1_expiry_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t02_t1_expiry_yes" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t02_t1_expiry_yes not found")
	}
	if tx.On != "T1_expiry" {
		t.Errorf("On = %q, want T1_expiry", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "RC_eq_N2" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "RC_eq_N2")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (G)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (G)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DL-DISCONNECT Indication" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DL-DISCONNECT Indication")
	}
	if tx.Actions[1].Kind != SignalUpper {
		t.Errorf("Actions[1].Kind = %v, want SignalUpper", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t02_t1_expiry_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t02_t1_expiry_no" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t02_t1_expiry_no not found")
	}
	if tx.On != "T1_expiry" {
		t.Errorf("On = %q, want T1_expiry", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "not RC_eq_N2" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not RC_eq_N2")
	}
	if got := len(tx.Actions); got != 4 {
		t.Fatalf("len(Actions) = %d, want 4", got)
	}
	if tx.Actions[0].Verb != "RC := RC + 1" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "RC := RC + 1")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DISC (P = 1)" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DISC (P = 1)")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Select_T1_Value" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Select_T1_Value")
	}
	if tx.Actions[2].Kind != Subroutine {
		t.Errorf("Actions[2].Kind = %v, want Subroutine", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "Start T1" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "Start T1")
	}
	if tx.Actions[3].Kind != Processing {
		t.Errorf("Actions[3].Kind = %v, want Processing", tx.Actions[3].Kind)
	}
}

func TestDataLinkAwaitingRelease_t03_ua_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t03_ua_received_yes" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t03_ua_received_yes not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "DL-DISCONNECT Confirm" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-DISCONNECT Confirm")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Stop T1" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Stop T1")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t03_ua_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t03_ua_received_no" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t03_ua_received_no not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "not F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not F_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (D)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (D)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t04_all_other_primitives__from_upper_layer(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t04_all_other_primitives__from_upper_layer" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t04_all_other_primitives__from_upper_layer not found")
	}
	if tx.On != "all_other_primitives__from_upper_layer" {
		t.Errorf("On = %q, want all_other_primitives__from_upper_layer", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingRelease_t05_dl_unit_data_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t05_dl_unit_data_request" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t05_dl_unit_data_request not found")
	}
	if tx.On != "DL_UNIT_DATA_request" {
		t.Errorf("On = %q, want DL_UNIT_DATA_request", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "UI Command" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI Command")
	}
	if tx.Actions[0].Kind != SignalLower {
		t.Errorf("Actions[0].Kind = %v, want SignalLower", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t06_all_other_primitives__from_lower_layer(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t06_all_other_primitives__from_lower_layer" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t06_all_other_primitives__from_lower_layer not found")
	}
	if tx.On != "all_other_primitives__from_lower_layer" {
		t.Errorf("On = %q, want all_other_primitives__from_lower_layer", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingRelease_t07_control_field_error(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t07_control_field_error" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t07_control_field_error not found")
	}
	if tx.On != "control_field_error" {
		t.Errorf("On = %q, want control_field_error", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (L)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (L)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t08_info_not_permitted_in_frame(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t08_info_not_permitted_in_frame" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t08_info_not_permitted_in_frame not found")
	}
	if tx.On != "info_not_permitted_in_frame" {
		t.Errorf("On = %q, want info_not_permitted_in_frame", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (M)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (M)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t09_u_or_s_frame_length_error(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t09_u_or_s_frame_length_error" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t09_u_or_s_frame_length_error not found")
	}
	if tx.On != "u_or_s_frame_length_error" {
		t.Errorf("On = %q, want u_or_s_frame_length_error", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (N)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (N)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t10_sabm_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t10_sabm_received" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t10_sabm_received not found")
	}
	if tx.On != "SABM_received" {
		t.Errorf("On = %q, want SABM_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Expedited DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Expedited DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t11_sabme_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t11_sabme_received" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t11_sabme_received not found")
	}
	if tx.On != "SABME_received" {
		t.Errorf("On = %q, want SABME_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Expedited DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Expedited DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t12_disc_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t12_disc_received" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t12_disc_received not found")
	}
	if tx.On != "DISC_received" {
		t.Errorf("On = %q, want DISC_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Expedited UA" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Expedited UA")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t13_dm_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t13_dm_received_yes" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t13_dm_received_yes not found")
	}
	if tx.On != "DM_received" {
		t.Errorf("On = %q, want DM_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "DL-DISCONNECT Confirm" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-DISCONNECT Confirm")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Stop T1" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Stop T1")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t13_dm_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t13_dm_received_no" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t13_dm_received_no not found")
	}
	if tx.On != "DM_received" {
		t.Errorf("On = %q, want DM_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "not F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not F_eq_1")
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingRelease_t14_ui_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t14_ui_received_yes" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t14_ui_received_yes not found")
	}
	if tx.On != "UI_received" {
		t.Errorf("On = %q, want UI_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "P_eq_1")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "UI Check" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI Check")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM (F = 1)" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM (F = 1)")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingRelease_t14_ui_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t14_ui_received_no" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t14_ui_received_no not found")
	}
	if tx.On != "UI_received" {
		t.Errorf("On = %q, want UI_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "not P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not P_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "UI Check" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI Check")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t15_i_or_s_command_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t15_i_or_s_command_received_yes" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t15_i_or_s_command_received_yes not found")
	}
	if tx.On != "i_or_s_command_received" {
		t.Errorf("On = %q, want i_or_s_command_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "P_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DM (F = 1)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DM (F = 1)")
	}
	if tx.Actions[0].Kind != SignalLower {
		t.Errorf("Actions[0].Kind = %v, want SignalLower", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingRelease_t15_i_or_s_command_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingRelease.Transitions {
		if DataLinkAwaitingRelease.Transitions[i].ID == "t15_i_or_s_command_received_no" {
			tx = &DataLinkAwaitingRelease.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t15_i_or_s_command_received_no not found")
	}
	if tx.On != "i_or_s_command_received" {
		t.Errorf("On = %q, want i_or_s_command_received", tx.On)
	}
	if tx.Next != "AwaitingRelease" {
		t.Errorf("Next = %q, want AwaitingRelease", tx.Next)
	}
	if tx.Guard != "not P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not P_eq_1")
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}
