// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/awaiting_v22_connection.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

import "testing"

func TestDataLinkAwaitingV22Connection_SourceFigure(t *testing.T) {
	if got := DataLinkAwaitingV22Connection.Source.Figure; got != "figc4.6" {
		t.Errorf("Source.Figure = %q, want figc4.6", got)
	}
}

func TestDataLinkAwaitingV22Connection_TransitionsArePresent(t *testing.T) {
	if got := len(DataLinkAwaitingV22Connection.Transitions); got != 25 {
		t.Errorf("len(Transitions) = %d, want 25", got)
	}
}

func TestDataLinkAwaitingV22Connection_t02_dl_connect_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t02_dl_connect_request" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t02_dl_connect_request not found")
	}
	if tx.On != "DL_CONNECT_request" {
		t.Errorf("On = %q, want DL_CONNECT_request", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "Discard Queue" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "Discard Queue")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Set Layer 3 Initiated" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Set Layer 3 Initiated")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t03_dl_unit_data_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t03_dl_unit_data_request" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t03_dl_unit_data_request not found")
	}
	if tx.On != "DL_UNIT_DATA_request" {
		t.Errorf("On = %q, want DL_UNIT_DATA_request", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "UI Command" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI Command")
	}
	if tx.Actions[0].Kind != SignalLower {
		t.Errorf("Actions[0].Kind = %v, want SignalLower", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t04_dl_data_request_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t04_dl_data_request_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t04_dl_data_request_yes not found")
	}
	if tx.On != "DL_DATA_request" {
		t.Errorf("On = %q, want DL_DATA_request", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "layer_3_initiated" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "layer_3_initiated")
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingV22Connection_t04_dl_data_request_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t04_dl_data_request_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t04_dl_data_request_no not found")
	}
	if tx.On != "DL_DATA_request" {
		t.Errorf("On = %q, want DL_DATA_request", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "not layer_3_initiated" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not layer_3_initiated")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "push_frame_on_queue" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "push_frame_on_queue")
	}
	if tx.Actions[0].Kind != InternalOut {
		t.Errorf("Actions[0].Kind = %v, want InternalOut", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t05_i_frame_pops_off_queue_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t05_i_frame_pops_off_queue_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t05_i_frame_pops_off_queue_yes not found")
	}
	if tx.On != "I_frame_pops_off_queue" {
		t.Errorf("On = %q, want I_frame_pops_off_queue", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "layer_3_initiated" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "layer_3_initiated")
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingV22Connection_t05_i_frame_pops_off_queue_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t05_i_frame_pops_off_queue_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t05_i_frame_pops_off_queue_no not found")
	}
	if tx.On != "I_frame_pops_off_queue" {
		t.Errorf("On = %q, want I_frame_pops_off_queue", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "not layer_3_initiated" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not layer_3_initiated")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "push_frame_on_queue" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "push_frame_on_queue")
	}
	if tx.Actions[0].Kind != InternalOut {
		t.Errorf("Actions[0].Kind = %v, want InternalOut", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t06_all_other_primitives__from_upper_layer(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t06_all_other_primitives__from_upper_layer" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t06_all_other_primitives__from_upper_layer not found")
	}
	if tx.On != "all_other_primitives__from_upper_layer" {
		t.Errorf("On = %q, want all_other_primitives__from_upper_layer", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingV22Connection_t07_control_field_error(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t07_control_field_error" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t07_control_field_error not found")
	}
	if tx.On != "control_field_error" {
		t.Errorf("On = %q, want control_field_error", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (L)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (L)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t08_info_not_permitted_in_frame(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t08_info_not_permitted_in_frame" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t08_info_not_permitted_in_frame not found")
	}
	if tx.On != "info_not_permitted_in_frame" {
		t.Errorf("On = %q, want info_not_permitted_in_frame", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (M)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (M)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t09_u_or_s_frame_length_error(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t09_u_or_s_frame_length_error" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t09_u_or_s_frame_length_error not found")
	}
	if tx.On != "u_or_s_frame_length_error" {
		t.Errorf("On = %q, want u_or_s_frame_length_error", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (N)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (N)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t10_ui_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t10_ui_received_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t10_ui_received_no not found")
	}
	if tx.On != "UI_received" {
		t.Errorf("On = %q, want UI_received", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "not P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not P_eq_1")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "UI Check" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI Check")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM (F = 1)" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM (F = 1)")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t10_ui_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t10_ui_received_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t10_ui_received_yes not found")
	}
	if tx.On != "UI_received" {
		t.Errorf("On = %q, want UI_received", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "P_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "UI Check" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI Check")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t11_dm_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t11_dm_received_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t11_dm_received_no not found")
	}
	if tx.On != "DM_received" {
		t.Errorf("On = %q, want DM_received", tx.On)
	}
	if tx.Next != "AwaitingConnection" {
		t.Errorf("Next = %q, want AwaitingConnection", tx.Next)
	}
	if tx.Guard != "not F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not F_eq_1")
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkAwaitingV22Connection_t11_dm_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t11_dm_received_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t11_dm_received_yes not found")
	}
	if tx.On != "DM_received" {
		t.Errorf("On = %q, want DM_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1")
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "discard_I_frame_queue" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "discard_I_frame_queue")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DL-DISCONNECT Indication" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DL-DISCONNECT Indication")
	}
	if tx.Actions[1].Kind != SignalUpper {
		t.Errorf("Actions[1].Kind = %v, want SignalUpper", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Stop T1" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Stop T1")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t12_ua_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t12_ua_received_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t12_ua_received_no not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "not F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not F_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL-ERROR Indication (D)" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-ERROR Indication (D)")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t12_ua_received_yes_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t12_ua_received_yes_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t12_ua_received_yes_yes not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "Connected" {
		t.Errorf("Next = %q, want Connected", tx.Next)
	}
	if tx.Guard != "F_eq_1 and layer_3_initiated" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1 and layer_3_initiated")
	}
	if got := len(tx.Actions); got != 8 {
		t.Fatalf("len(Actions) = %d, want 8", got)
	}
	if tx.Actions[0].Verb != "DL-CONNECT Confirm" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL-CONNECT Confirm")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Stop T1" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Stop T1")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Start T3" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Start T3")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "V(s) := 0" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "V(s) := 0")
	}
	if tx.Actions[3].Kind != Processing {
		t.Errorf("Actions[3].Kind = %v, want Processing", tx.Actions[3].Kind)
	}
	if tx.Actions[4].Verb != "V(a) := 0" {
		t.Errorf("Actions[4].Verb = %q, want %q", tx.Actions[4].Verb, "V(a) := 0")
	}
	if tx.Actions[4].Kind != Processing {
		t.Errorf("Actions[4].Kind = %v, want Processing", tx.Actions[4].Kind)
	}
	if tx.Actions[5].Verb != "V(r) := 0" {
		t.Errorf("Actions[5].Verb = %q, want %q", tx.Actions[5].Verb, "V(r) := 0")
	}
	if tx.Actions[5].Kind != Processing {
		t.Errorf("Actions[5].Kind = %v, want Processing", tx.Actions[5].Kind)
	}
	if tx.Actions[6].Verb != "Select_T1_Value" {
		t.Errorf("Actions[6].Verb = %q, want %q", tx.Actions[6].Verb, "Select_T1_Value")
	}
	if tx.Actions[6].Kind != Subroutine {
		t.Errorf("Actions[6].Kind = %v, want Subroutine", tx.Actions[6].Kind)
	}
	if tx.Actions[7].Verb != "MDL-NEGOTIATE Request" {
		t.Errorf("Actions[7].Verb = %q, want %q", tx.Actions[7].Verb, "MDL-NEGOTIATE Request")
	}
	if tx.Actions[7].Kind != InternalOut {
		t.Errorf("Actions[7].Kind = %v, want InternalOut", tx.Actions[7].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t12_ua_received_yes_no_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t12_ua_received_yes_no_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t12_ua_received_yes_no_no not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "Connected" {
		t.Errorf("Next = %q, want Connected", tx.Next)
	}
	if tx.Guard != "F_eq_1 and not layer_3_initiated and not vs_eq_va" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1 and not layer_3_initiated and not vs_eq_va")
	}
	if got := len(tx.Actions); got != 11 {
		t.Fatalf("len(Actions) = %d, want 11", got)
	}
	if tx.Actions[0].Verb != "SRT := Initial Default" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "SRT := Initial Default")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "T1V := 2 * SRT" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "T1V := 2 * SRT")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Start T3" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Start T3")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "DL-CONNECT Confirm" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "DL-CONNECT Confirm")
	}
	if tx.Actions[3].Kind != SignalUpper {
		t.Errorf("Actions[3].Kind = %v, want SignalUpper", tx.Actions[3].Kind)
	}
	if tx.Actions[4].Verb != "Stop T1" {
		t.Errorf("Actions[4].Verb = %q, want %q", tx.Actions[4].Verb, "Stop T1")
	}
	if tx.Actions[4].Kind != Processing {
		t.Errorf("Actions[4].Kind = %v, want Processing", tx.Actions[4].Kind)
	}
	if tx.Actions[5].Verb != "Start T3" {
		t.Errorf("Actions[5].Verb = %q, want %q", tx.Actions[5].Verb, "Start T3")
	}
	if tx.Actions[5].Kind != Processing {
		t.Errorf("Actions[5].Kind = %v, want Processing", tx.Actions[5].Kind)
	}
	if tx.Actions[6].Verb != "V(s) := 0" {
		t.Errorf("Actions[6].Verb = %q, want %q", tx.Actions[6].Verb, "V(s) := 0")
	}
	if tx.Actions[6].Kind != Processing {
		t.Errorf("Actions[6].Kind = %v, want Processing", tx.Actions[6].Kind)
	}
	if tx.Actions[7].Verb != "V(a) := 0" {
		t.Errorf("Actions[7].Verb = %q, want %q", tx.Actions[7].Verb, "V(a) := 0")
	}
	if tx.Actions[7].Kind != Processing {
		t.Errorf("Actions[7].Kind = %v, want Processing", tx.Actions[7].Kind)
	}
	if tx.Actions[8].Verb != "V(r) := 0" {
		t.Errorf("Actions[8].Verb = %q, want %q", tx.Actions[8].Verb, "V(r) := 0")
	}
	if tx.Actions[8].Kind != Processing {
		t.Errorf("Actions[8].Kind = %v, want Processing", tx.Actions[8].Kind)
	}
	if tx.Actions[9].Verb != "Select_T1_Value" {
		t.Errorf("Actions[9].Verb = %q, want %q", tx.Actions[9].Verb, "Select_T1_Value")
	}
	if tx.Actions[9].Kind != Subroutine {
		t.Errorf("Actions[9].Kind = %v, want Subroutine", tx.Actions[9].Kind)
	}
	if tx.Actions[10].Verb != "MDL-NEGOTIATE Request" {
		t.Errorf("Actions[10].Verb = %q, want %q", tx.Actions[10].Verb, "MDL-NEGOTIATE Request")
	}
	if tx.Actions[10].Kind != InternalOut {
		t.Errorf("Actions[10].Kind = %v, want InternalOut", tx.Actions[10].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t12_ua_received_yes_no_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t12_ua_received_yes_no_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t12_ua_received_yes_no_yes not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "Connected" {
		t.Errorf("Next = %q, want Connected", tx.Next)
	}
	if tx.Guard != "F_eq_1 and not layer_3_initiated and vs_eq_va" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1 and not layer_3_initiated and vs_eq_va")
	}
	if got := len(tx.Actions); got != 7 {
		t.Fatalf("len(Actions) = %d, want 7", got)
	}
	if tx.Actions[0].Verb != "Stop T1" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "Stop T1")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Start T3" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Start T3")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "V(s) := 0" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "V(s) := 0")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "V(a) := 0" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "V(a) := 0")
	}
	if tx.Actions[3].Kind != Processing {
		t.Errorf("Actions[3].Kind = %v, want Processing", tx.Actions[3].Kind)
	}
	if tx.Actions[4].Verb != "V(r) := 0" {
		t.Errorf("Actions[4].Verb = %q, want %q", tx.Actions[4].Verb, "V(r) := 0")
	}
	if tx.Actions[4].Kind != Processing {
		t.Errorf("Actions[4].Kind = %v, want Processing", tx.Actions[4].Kind)
	}
	if tx.Actions[5].Verb != "Select_T1_Value" {
		t.Errorf("Actions[5].Verb = %q, want %q", tx.Actions[5].Verb, "Select_T1_Value")
	}
	if tx.Actions[5].Kind != Subroutine {
		t.Errorf("Actions[5].Kind = %v, want Subroutine", tx.Actions[5].Kind)
	}
	if tx.Actions[6].Verb != "MDL-NEGOTIATE Request" {
		t.Errorf("Actions[6].Verb = %q, want %q", tx.Actions[6].Verb, "MDL-NEGOTIATE Request")
	}
	if tx.Actions[6].Kind != InternalOut {
		t.Errorf("Actions[6].Kind = %v, want InternalOut", tx.Actions[6].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t13_t1_expiry_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t13_t1_expiry_yes" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t13_t1_expiry_yes not found")
	}
	if tx.On != "T1_expiry" {
		t.Errorf("On = %q, want T1_expiry", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "RC_eq_N2" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "RC_eq_N2")
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "discard_frame_queue" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "discard_frame_queue")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DL-ERROR Indication (G)" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DL-ERROR Indication (G)")
	}
	if tx.Actions[1].Kind != SignalUpper {
		t.Errorf("Actions[1].Kind = %v, want SignalUpper", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "DL-DISCONNECT Indication" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "DL-DISCONNECT Indication")
	}
	if tx.Actions[2].Kind != SignalUpper {
		t.Errorf("Actions[2].Kind = %v, want SignalUpper", tx.Actions[2].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t13_t1_expiry_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t13_t1_expiry_no" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t13_t1_expiry_no not found")
	}
	if tx.On != "T1_expiry" {
		t.Errorf("On = %q, want T1_expiry", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if tx.Guard != "not RC_eq_N2" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not RC_eq_N2")
	}
	if got := len(tx.Actions); got != 4 {
		t.Fatalf("len(Actions) = %d, want 4", got)
	}
	if tx.Actions[0].Verb != "RC := RC + 1" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "RC := RC + 1")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "SABME (P = 1)" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "SABME (P = 1)")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Select_T1_Value" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Select_T1_Value")
	}
	if tx.Actions[2].Kind != Subroutine {
		t.Errorf("Actions[2].Kind = %v, want Subroutine", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "Start T1" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "Start T1")
	}
	if tx.Actions[3].Kind != Processing {
		t.Errorf("Actions[3].Kind = %v, want Processing", tx.Actions[3].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t14_frmr_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t14_frmr_received" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t14_frmr_received not found")
	}
	if tx.On != "FRMR_received" {
		t.Errorf("On = %q, want FRMR_received", tx.On)
	}
	if tx.Next != "AwaitingConnection" {
		t.Errorf("Next = %q, want AwaitingConnection", tx.Next)
	}
	if got := len(tx.Actions); got != 5 {
		t.Fatalf("len(Actions) = %d, want 5", got)
	}
	if tx.Actions[0].Verb != "SRT := Initial Default" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "SRT := Initial Default")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "T1V := 2 * SRT" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "T1V := 2 * SRT")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Establish_Data_Link" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Establish_Data_Link")
	}
	if tx.Actions[2].Kind != Subroutine {
		t.Errorf("Actions[2].Kind = %v, want Subroutine", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "Set Layer 3 Initiated" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "Set Layer 3 Initiated")
	}
	if tx.Actions[3].Kind != Processing {
		t.Errorf("Actions[3].Kind = %v, want Processing", tx.Actions[3].Kind)
	}
	if tx.Actions[4].Verb != "set_version_2_0" {
		t.Errorf("Actions[4].Verb = %q, want %q", tx.Actions[4].Verb, "set_version_2_0")
	}
	if tx.Actions[4].Kind != Processing {
		t.Errorf("Actions[4].Kind = %v, want Processing", tx.Actions[4].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t15_sabme_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t15_sabme_received" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t15_sabme_received not found")
	}
	if tx.On != "SABME_received" {
		t.Errorf("On = %q, want SABME_received", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "UA" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "UA")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t16_sabm_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t16_sabm_received" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t16_sabm_received not found")
	}
	if tx.On != "SABM_received" {
		t.Errorf("On = %q, want SABM_received", tx.On)
	}
	if tx.Next != "AwaitingConnection" {
		t.Errorf("Next = %q, want AwaitingConnection", tx.Next)
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "UA" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "UA")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "set_version_2_0" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "set_version_2_0")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t17_disc_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t17_disc_received" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t17_disc_received not found")
	}
	if tx.On != "DISC_received" {
		t.Errorf("On = %q, want DISC_received", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkAwaitingV22Connection_t18_all_other_primitives__from_lower_layer(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkAwaitingV22Connection.Transitions {
		if DataLinkAwaitingV22Connection.Transitions[i].ID == "t18_all_other_primitives__from_lower_layer" {
			tx = &DataLinkAwaitingV22Connection.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t18_all_other_primitives__from_lower_layer not found")
	}
	if tx.On != "all_other_primitives__from_lower_layer" {
		t.Errorf("On = %q, want all_other_primitives__from_lower_layer", tx.On)
	}
	if tx.Next != "AwaitingV22Connection" {
		t.Errorf("Next = %q, want AwaitingV22Connection", tx.Next)
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}
