// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/management-data-link/yaml/negotiating.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

import "testing"

func TestManagementDataLinkNegotiating_SourceFigure(t *testing.T) {
	if got := ManagementDataLinkNegotiating.Source.Figure; got != "figc5.2" {
		t.Errorf("Source.Figure = %q, want figc5.2", got)
	}
}

func TestManagementDataLinkNegotiating_TransitionsArePresent(t *testing.T) {
	if got := len(ManagementDataLinkNegotiating.Transitions); got != 5 {
		t.Errorf("len(Transitions) = %d, want 5", got)
	}
}

func TestManagementDataLinkNegotiating_t01_xid_response_received_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkNegotiating.Transitions {
		if ManagementDataLinkNegotiating.Transitions[i].ID == "t01_xid_response_received_yes" {
			tx = &ManagementDataLinkNegotiating.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t01_xid_response_received_yes not found")
	}
	if tx.On != "XID_response_received" {
		t.Errorf("On = %q, want XID_response_received", tx.On)
	}
	if tx.Next != "Ready" {
		t.Errorf("Next = %q, want Ready", tx.Next)
	}
	if tx.Guard != "F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "F_eq_1")
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "Apply Negotiated Parameters" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "Apply Negotiated Parameters")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Stop TM201" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Stop TM201")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "MDL_NEGOTIATE_confirm" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "MDL_NEGOTIATE_confirm")
	}
	if tx.Actions[2].Kind != SignalUpper {
		t.Errorf("Actions[2].Kind = %v, want SignalUpper", tx.Actions[2].Kind)
	}
}

func TestManagementDataLinkNegotiating_t01_xid_response_received_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkNegotiating.Transitions {
		if ManagementDataLinkNegotiating.Transitions[i].ID == "t01_xid_response_received_no" {
			tx = &ManagementDataLinkNegotiating.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t01_xid_response_received_no not found")
	}
	if tx.On != "XID_response_received" {
		t.Errorf("On = %q, want XID_response_received", tx.On)
	}
	if tx.Next != "Negotiating" {
		t.Errorf("Next = %q, want Negotiating", tx.Next)
	}
	if tx.Guard != "not F_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not F_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "MDL_ERROR_indicate_D" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "MDL_ERROR_indicate_D")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestManagementDataLinkNegotiating_t02_frmr_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkNegotiating.Transitions {
		if ManagementDataLinkNegotiating.Transitions[i].ID == "t02_frmr_received" {
			tx = &ManagementDataLinkNegotiating.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t02_frmr_received not found")
	}
	if tx.On != "FRMR_received" {
		t.Errorf("On = %q, want FRMR_received", tx.On)
	}
	if tx.Next != "Ready" {
		t.Errorf("Next = %q, want Ready", tx.Next)
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "set_version_2_0" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "set_version_2_0")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "Stop TM201" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "Stop TM201")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "MDL_NEGOTIATE_confirm" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "MDL_NEGOTIATE_confirm")
	}
	if tx.Actions[2].Kind != SignalUpper {
		t.Errorf("Actions[2].Kind = %v, want SignalUpper", tx.Actions[2].Kind)
	}
}

func TestManagementDataLinkNegotiating_t03_tm201_expiry_yes(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkNegotiating.Transitions {
		if ManagementDataLinkNegotiating.Transitions[i].ID == "t03_tm201_expiry_yes" {
			tx = &ManagementDataLinkNegotiating.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t03_tm201_expiry_yes not found")
	}
	if tx.On != "TM201_expiry" {
		t.Errorf("On = %q, want TM201_expiry", tx.On)
	}
	if tx.Next != "Ready" {
		t.Errorf("Next = %q, want Ready", tx.Next)
	}
	if tx.Guard != "RC_eq_NM201" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "RC_eq_NM201")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "MDL_ERROR_indicate_C" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "MDL_ERROR_indicate_C")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestManagementDataLinkNegotiating_t03_tm201_expiry_no(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkNegotiating.Transitions {
		if ManagementDataLinkNegotiating.Transitions[i].ID == "t03_tm201_expiry_no" {
			tx = &ManagementDataLinkNegotiating.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t03_tm201_expiry_no not found")
	}
	if tx.On != "TM201_expiry" {
		t.Errorf("On = %q, want TM201_expiry", tx.On)
	}
	if tx.Next != "Negotiating" {
		t.Errorf("Next = %q, want Negotiating", tx.Next)
	}
	if tx.Guard != "not RC_eq_NM201" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not RC_eq_NM201")
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "RC := RC + 1" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "RC := RC + 1")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "XID_command" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "XID_command")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Start TM201" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Start TM201")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
}
