// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/management-data-link/yaml/ready.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

// ManagementDataLinkReady holds the SDL transitions for the
// Ready state of the management_data_link machine. Source: ax.25.2.2.4_Oct_25, figure figc5.1.
var ManagementDataLinkReady = StatePage{
	Machine: "management_data_link",
	State:   "Ready",
	Source:  SdlSource{Spec: "ax.25.2.2.4_Oct_25", Figure: "figc5.1", URL: "https://raw.githubusercontent.com/packethacking/ax25spec/main/doc/ax.25.2.2.4_Oct_25.md"},
	Transitions: []TransitionSpec{
		{
			ID:    "t01_mdl_negotiate_request",
			From:  "Ready",
			On:    "MDL_NEGOTIATE_request",
			Guard: "",
			Actions: []ActionStep{
				{Verb: "RC := 0", Kind: Processing},
				{Verb: "XID_command", Kind: SignalLower},
				{Verb: "Start TM201", Kind: Processing},
			},
			Next:  "Negotiating",
			Notes: "verification_pending (prose-derived bootstrap; figc5.1 graphml redraw pending — see backfill task). Derived from Appendix C5.3 ¶3 (\"The station initiating the AX.25 connection will send an XID command after it receives the UA frame\") + C5.3 Variables/Timers (RC, NM201, TM201). The ORDER of the three steps (RC:=0, send XID, start TM201) and the XID command's P=1 bit are NOT stated by the prose — error A (\"XID command without P=1\", C5.3 Error Codes) implies the command carries P=1, but the exact action ordering and the P-bit assignment box are figc5.1 detail and unverified. The DL→MDL handoff that raises this input is the data-link figc4.6 (AwaitingV22Connection) UA-received path, which emits `MDL-NEGOTIATE Request` (internal_out) on a successful v2.2 connect — see spec-sdl/.../data-link/yaml/awaiting_v22_connection.sdl.yaml.",
			References: []ImplementationReference{
				{Source: "spec_prose", Cite: "§C5.3 ¶3", Quote: "The station initiating the AX.25 connection will send an XID command after it receives the UA frame.", Path: "", Function: "", Line: 0, Note: ""},
				{Source: "spec_prose", Cite: "§6.3.2 ¶1", Quote: "Parameter negotiation occurs only before the connection is made. It is accomplished by sending the XID command frame and receiving the XID response frame.", Path: "", Function: "", Line: 0, Note: ""},
				{Source: "spec_prose", Cite: "§5.1", Quote: "MDL-NEGOTIATE Request. The Layer 3 entity uses this primitive to request the Data-link State Machine to notify/negotiate.", Path: "", Function: "", Line: 0, Note: ""},
			},
			Loops: []LoopRange{},
		},
		{
			ID:    "t02_xid_response_received",
			From:  "Ready",
			On:    "XID_response_received",
			Guard: "",
			Actions: []ActionStep{
				{Verb: "MDL_ERROR_indicate_B", Kind: SignalUpper},
			},
			Next:  "Ready",
			Notes: "verification_pending (prose-derived bootstrap; figc5.1 graphml redraw pending — see backfill task). The EXISTENCE of error B (\"Unexpected XID response\", §C5.3 Error Codes) is prose-clear, and Ready is the defensible state for it (no XID command outstanding). But the figc5.1 column for a received XID response — whether it is drawn at all in Ready, what (if any) frame is emitted, and the precise MDL-ERROR letter wiring — is unverified figure detail. Encoded as the most defensible reading of the error-code list, NOT from a figure.",
			References: []ImplementationReference{
				{Source: "spec_prose", Cite: "§C5.3 Error Codes", Quote: "B — Unexpected XID response.", Path: "", Function: "", Line: 0, Note: ""},
			},
			Loops: []LoopRange{},
		},
	},
}
