// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/management-data-link/yaml/ready.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

import "testing"

func TestManagementDataLinkReady_SourceFigure(t *testing.T) {
	if got := ManagementDataLinkReady.Source.Figure; got != "figc5.1" {
		t.Errorf("Source.Figure = %q, want figc5.1", got)
	}
}

func TestManagementDataLinkReady_TransitionsArePresent(t *testing.T) {
	if got := len(ManagementDataLinkReady.Transitions); got != 2 {
		t.Errorf("len(Transitions) = %d, want 2", got)
	}
}

func TestManagementDataLinkReady_t01_mdl_negotiate_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkReady.Transitions {
		if ManagementDataLinkReady.Transitions[i].ID == "t01_mdl_negotiate_request" {
			tx = &ManagementDataLinkReady.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t01_mdl_negotiate_request not found")
	}
	if tx.On != "MDL_NEGOTIATE_request" {
		t.Errorf("On = %q, want MDL_NEGOTIATE_request", tx.On)
	}
	if tx.Next != "Negotiating" {
		t.Errorf("Next = %q, want Negotiating", tx.Next)
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "RC := 0" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "RC := 0")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "XID_command" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "XID_command")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Start TM201" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Start TM201")
	}
	if tx.Actions[2].Kind != Processing {
		t.Errorf("Actions[2].Kind = %v, want Processing", tx.Actions[2].Kind)
	}
}

func TestManagementDataLinkReady_t02_xid_response_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range ManagementDataLinkReady.Transitions {
		if ManagementDataLinkReady.Transitions[i].ID == "t02_xid_response_received" {
			tx = &ManagementDataLinkReady.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t02_xid_response_received not found")
	}
	if tx.On != "XID_response_received" {
		t.Errorf("On = %q, want XID_response_received", tx.On)
	}
	if tx.Next != "Ready" {
		t.Errorf("Next = %q, want Ready", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "MDL_ERROR_indicate_B" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "MDL_ERROR_indicate_B")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}
