// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/subroutines.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

// DataLinkSubroutines holds the SDL subroutines for the
// data_link machine. Source: ax.25.2.2.4_Oct_25, figure figc4.7.
var DataLinkSubroutines = SubroutinesPage{
	Machine: "data_link",
	Source:  SdlSource{Spec: "ax.25.2.2.4_Oct_25", Figure: "figc4.7", URL: ""},
	Subroutines: []SubroutineSpec{
		{
			Name: "Set_Version_2_2",
			Paths: []SubroutinePath{
				{
					ID:    "t01_set_version_2_2",
					Guard: "",
					Actions: []ActionStep{
						{Verb: "Set Half Duplex", Kind: Processing},
						{Verb: "Set Selective Reject", Kind: Processing},
						{Verb: "Modulo := 128", Kind: Processing},
						{Verb: "N1 := 2048", Kind: Processing},
						{Verb: "k := 32", Kind: Processing},
						{Verb: "T2 := 3000", Kind: Processing},
						{Verb: "N2 := 10", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "UI_Check",
			Paths: []SubroutinePath{
				{
					ID:    "t01_ui_check_no",
					Guard: "not command",
					Actions: []ActionStep{
						{Verb: "DL-ERROR Indication (Q)", Kind: SignalUpper},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t02_ui_check_yes_yes",
					Guard: "command and info_field_length_le_N1_&_content_is_octet_aligned",
					Actions: []ActionStep{
						{Verb: "DL-UNIT-DATA Indication", Kind: SignalUpper},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t03_ui_check_yes_no",
					Guard: "command and not info_field_length_le_N1_&_content_is_octet_aligned",
					Actions: []ActionStep{
						{Verb: "DL-ERROR Indication (K)", Kind: SignalUpper},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Select_T1",
			Paths: []SubroutinePath{
				{
					ID:    "t01_select_t1_yes",
					Guard: "RC_eq_0",
					Actions: []ActionStep{
						{Verb: "SRT := 7(SRT)/8 + (T1)/8 - (Remaining Time on T1 When Last Stopped)/8", Kind: Processing},
						{Verb: "Next T1 := 2 * SRT", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:         "t02_select_t1_no_no",
					Guard:      "not RC_eq_0 and not T1_expired",
					Actions:    []ActionStep{},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t03_select_t1_no_yes",
					Guard: "not RC_eq_0 and T1_expired",
					Actions: []ActionStep{
						{Verb: "Next T1 := (RC*0.25)+SRT*2", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Set_Version_2_0",
			Paths: []SubroutinePath{
				{
					ID:    "t01_set_version_2_0",
					Guard: "",
					Actions: []ActionStep{
						{Verb: "Set Half Duplex", Kind: Processing},
						{Verb: "Set Implicit Reject", Kind: Processing},
						{Verb: "Modulo := 8", Kind: Processing},
						{Verb: "N1 := 2048", Kind: Processing},
						{Verb: "k := 8", Kind: Processing},
						{Verb: "T2 := 3000", Kind: Processing},
						{Verb: "N2 := 10", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Check_Need_for_Response",
			Paths: []SubroutinePath{
				{
					ID:    "t01_check_need_for_response_yes",
					Guard: "command_&_P_eq_1",
					Actions: []ActionStep{
						{Verb: "Enquiry_Response_F_1", Kind: Subroutine},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:         "t02_check_need_for_response_no_no",
					Guard:      "not command_&_P_eq_1 and not response_&_F_eq_1",
					Actions:    []ActionStep{},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t03_check_need_for_response_no_yes",
					Guard: "not command_&_P_eq_1 and response_&_F_eq_1",
					Actions: []ActionStep{
						{Verb: "DL-ERROR Indication (A)", Kind: SignalUpper},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Invoke_Retransmission",
			Paths: []SubroutinePath{
				{
					ID:    "t01_invoke_retransmission_yes",
					Guard: "vs_eq_X",
					Actions: []ActionStep{
						{Verb: "Backtrack", Kind: Processing},
						{Verb: "X := V(s)", Kind: Processing},
						{Verb: "V(s) := N(r)", Kind: Processing},
						{Verb: "Push Old I Frame onto Queue", Kind: InternalOut},
						{Verb: "V(s) := V(s) + 1", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Check_I_Frame_Acknowledged",
			Paths: []SubroutinePath{
				{
					ID:    "t01_check_i_frame_acknowledged_yes_yes",
					Guard: "peer_receiver_busy and T1_running",
					Actions: []ActionStep{
						{Verb: "V(a) := N(r)", Kind: Processing},
						{Verb: "Stop T3", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t02_check_i_frame_acknowledged_yes_no",
					Guard: "peer_receiver_busy and not T1_running",
					Actions: []ActionStep{
						{Verb: "V(a) := N(r)", Kind: Processing},
						{Verb: "Stop T3", Kind: Processing},
						{Verb: "Start T1", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t03_check_i_frame_acknowledged_no_yes",
					Guard: "not peer_receiver_busy and nr_eq_vs",
					Actions: []ActionStep{
						{Verb: "V(a) := N(r)", Kind: Processing},
						{Verb: "Stop T1", Kind: Processing},
						{Verb: "Start T3", Kind: Processing},
						{Verb: "Select_T1_Value", Kind: Subroutine},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:         "t04_check_i_frame_acknowledged_no_no_yes",
					Guard:      "not peer_receiver_busy and not nr_eq_vs and nr_eq_va",
					Actions:    []ActionStep{},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t05_check_i_frame_acknowledged_no_no_no",
					Guard: "not peer_receiver_busy and not nr_eq_vs and not nr_eq_va",
					Actions: []ActionStep{
						{Verb: "V(a) := N(r)", Kind: Processing},
						{Verb: "Start T1", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Clear_Exception_Conditions",
			Paths: []SubroutinePath{
				{
					ID:    "t01_clear_exception_conditions",
					Guard: "",
					Actions: []ActionStep{
						{Verb: "Clear Peer Receiver Busy", Kind: Processing},
						{Verb: "Clear Own Receiver Busy", Kind: Processing},
						{Verb: "Clear Reject Condition", Kind: Processing},
						{Verb: "Clear Sreject Condition", Kind: Processing},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
						{Verb: "Discard I Queue Entries", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "N_r_Error_Recovery",
			Paths: []SubroutinePath{
				{
					ID:    "t01_n_r_error_recovery",
					Guard: "",
					Actions: []ActionStep{
						{Verb: "DL-ERROR Indication (J)", Kind: SignalUpper},
						{Verb: "Establish_Data_Link", Kind: Subroutine},
						{Verb: "Clear Layer 3 Initiated", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Transmit_Enquiry",
			Paths: []SubroutinePath{
				{
					ID:    "t01_transmit_enquiry_no",
					Guard: "not own_receiver_busy",
					Actions: []ActionStep{
						{Verb: "P := 1", Kind: Processing},
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "RR Command", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
						{Verb: "Start T1", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t02_transmit_enquiry_yes",
					Guard: "own_receiver_busy",
					Actions: []ActionStep{
						{Verb: "P := 1", Kind: Processing},
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "RNR Command", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
						{Verb: "Start T1", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
		{
			Name: "Enquiry_Response",
			Paths: []SubroutinePath{
				{
					ID:    "t01_enquiry_response_yes_yes",
					Guard: "F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi and own_receiver_busy",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "RNR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t02_enquiry_response_yes_no_yes_yes_yes",
					Guard: "F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi and not own_receiver_busy and SREJ_enabled and mod_8 and out_of_sequence_frames_in_receive_buffer",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "DL-ERROR Indication (add)", Kind: SignalUpper},
						{Verb: "SREJ", Kind: SignalLower},
						{Verb: "RR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t03_enquiry_response_yes_no_yes_yes_no",
					Guard: "F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi and not own_receiver_busy and SREJ_enabled and mod_8 and not out_of_sequence_frames_in_receive_buffer",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "DL-ERROR Indication (add)", Kind: SignalUpper},
						{Verb: "RR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t04_enquiry_response_yes_no_yes_no_yes",
					Guard: "F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi and not own_receiver_busy and SREJ_enabled and not mod_8 and out_of_sequence_frames_in_receive_buffer",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "SREJ", Kind: SignalLower},
						{Verb: "RR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t05_enquiry_response_yes_no_yes_no_no",
					Guard: "F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi and not own_receiver_busy and SREJ_enabled and not mod_8 and not out_of_sequence_frames_in_receive_buffer",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "RR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t06_enquiry_response_yes_no_no",
					Guard: "F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi and not own_receiver_busy and not SREJ_enabled",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "RR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
				{
					ID:    "t07_enquiry_response_no",
					Guard: "not F_eq_1_&_frameeqrr_||_frameeqrnr_||_frameeqi",
					Actions: []ActionStep{
						{Verb: "N(r) := V(r)", Kind: Processing},
						{Verb: "RR Response", Kind: SignalLower},
						{Verb: "Clear Acknowledge Pending", Kind: Processing},
					},
					Notes:      "",
					References: []ImplementationReference{},
					Loops:      []LoopRange{},
				},
			},
			Notes:      "",
			References: []ImplementationReference{},
		},
	},
}
