// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Linq;
using AwesomeAssertions;
using Packet.Ax25.Sdl;
using Xunit;

namespace Packet.Ax25.Conformance.Tests;

public class DataLink_Connected_GeneratedTests
{
    [Fact] public void SourceFigure() => DataLink_Connected.Source.Figure.Should().Be("figc4.4");

    [Fact] public void TransitionsArePresent() => DataLink_Connected.Transitions.Count.Should().Be(66);

    [Fact] public void t01_dl_disconnect_request()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t01_dl_disconnect_request");
        t.On.Should().Be("DL_DISCONNECT_request");
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("RC := 0");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("DISC (P = 1)");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be("Stop T3");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Start T1");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t02_dl_data_request()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t02_dl_data_request");
        t.On.Should().Be("DL_DATA_request");
        t.Next.Should().Be("Connected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("Push on I Frame Queue (note: word order?)");
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t03_i_frame_pops_off_queue_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_yes");
        t.On.Should().Be("I_frame_pops_off_queue");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("peer_receiver_busy");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("Push on I Frame Queue");
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t03_i_frame_pops_off_queue_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_no_yes");
        t.On.Should().Be("I_frame_pops_off_queue");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not peer_receiver_busy and vs_eq_va_plus_k");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("Push on I Frame Queue");
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t03_i_frame_pops_off_queue_no_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_no_no_no");
        t.On.Should().Be("I_frame_pops_off_queue");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not peer_receiver_busy and not vs_eq_va_plus_k and not T1_running");
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be("N(s) := V(s)");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("N(r) := V(r)");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("p := 0");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("I Command");
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[4].Verb.Should().Be("V(s) := V(s) + 1");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("Stop T3");
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be("Start T1");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t03_i_frame_pops_off_queue_no_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_no_no_yes");
        t.On.Should().Be("I_frame_pops_off_queue");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not peer_receiver_busy and not vs_eq_va_plus_k and T1_running");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be("N(s) := V(s)");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("N(r) := V(r)");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("p := 0");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("I Command");
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[4].Verb.Should().Be("V(s) := V(s) + 1");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t04_dl_unit_data_request()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t04_dl_unit_data_request");
        t.On.Should().Be("DL_UNIT_DATA_request");
        t.Next.Should().Be("Connected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("UI Command");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t05_dl_flow_off_request_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t05_dl_flow_off_request_yes");
        t.On.Should().Be("DL_FLOW_OFF_request");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("own_receiver_busy");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("Set Own Receiver Busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("RNR Response");
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t05_dl_flow_off_request_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t05_dl_flow_off_request_no");
        t.On.Should().Be("DL_FLOW_OFF_request");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not own_receiver_busy");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t06_dl_flow_on_request_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t06_dl_flow_on_request_no");
        t.On.Should().Be("DL_FLOW_ON_request");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not own_receiver_busy");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t06_dl_flow_on_request_yes_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t06_dl_flow_on_request_yes_yes");
        t.On.Should().Be("DL_FLOW_ON_request");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("own_receiver_busy and T1_running");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("Clear Own Receiver Busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("RR Command");
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t06_dl_flow_on_request_yes_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t06_dl_flow_on_request_yes_no");
        t.On.Should().Be("DL_FLOW_ON_request");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("own_receiver_busy and not T1_running");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be("Clear Own Receiver Busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("RR Command");
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Stop T3");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Start T1");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t07_dl_connect_request_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t07_dl_connect_request_no");
        t.On.Should().Be("DL_CONNECT_request");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t07_dl_connect_request_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t07_dl_connect_request_yes");
        t.On.Should().Be("DL_CONNECT_request");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t08_all_other_primitives__from_upper_layer()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t08_all_other_primitives__from_upper_layer");
        t.On.Should().Be("all_other_primitives__from_upper_layer");
        t.Next.Should().Be("Connected");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t09_control_field_error_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t09_control_field_error_no");
        t.On.Should().Be("control_field_error");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not version_2_2");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (L)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Establish_Data_Link");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t09_control_field_error_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t09_control_field_error_yes");
        t.On.Should().Be("control_field_error");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("version_2_2");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (L)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Establish_Data_Link");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t10_info_not_permitted_in_frame_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t10_info_not_permitted_in_frame_no");
        t.On.Should().Be("info_not_permitted_in_frame");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not version_2_2");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (M)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Establish_Data_Link");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t10_info_not_permitted_in_frame_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t10_info_not_permitted_in_frame_yes");
        t.On.Should().Be("info_not_permitted_in_frame");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("version_2_2");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (M)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Establish_Data_Link");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t11_u_or_s_frame_length_error_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t11_u_or_s_frame_length_error_no");
        t.On.Should().Be("u_or_s_frame_length_error");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not version_2_2");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (N)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Establish_Data_Link");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t11_u_or_s_frame_length_error_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t11_u_or_s_frame_length_error_yes");
        t.On.Should().Be("u_or_s_frame_length_error");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("version_2_2");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (N)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Establish_Data_Link");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be("Set Layer 3 Initiated");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t12_t1_expiry()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t12_t1_expiry");
        t.On.Should().Be("T1_expiry");
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be("RC := 1");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Transmit Enquery");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t13_t3_expiry()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t13_t3_expiry");
        t.On.Should().Be("T3_expiry");
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be("RC := 1");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Transmit Enquery");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t14_sabm_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t14_sabm_received_yes");
        t.On.Should().Be("SABM_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("vs_eq_va");
        t.Actions.Count.Should().Be(11);
        t.Actions[0].Verb.Should().Be("F := P");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("set_version_2_0");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("UA");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be("Clear Exception Conditions");
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be("DL-ERROR Indication (F)");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be("Stop T1");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("Start T3");
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be("V(a) := 0");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be("V(s) := 0");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be("V(r) := 0");
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be("RC := 0");
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t14_sabm_received_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t14_sabm_received_no");
        t.On.Should().Be("SABM_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not vs_eq_va");
        t.Actions.Count.Should().Be(13);
        t.Actions[0].Verb.Should().Be("F := P");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("set_version_2_0");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("UA");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be("Clear Exception Conditions");
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be("DL-ERROR Indication (F)");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("DL-CONNECT Indication");
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be("Stop T1");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be("Start T3");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be("V(a) := 0");
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be("V(s) := 0");
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
        t.Actions[11].Verb.Should().Be("V(r) := 0");
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
        t.Actions[12].Verb.Should().Be("RC := 0");
        t.Actions[12].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t15_sabme_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t15_sabme_received_yes");
        t.On.Should().Be("SABME_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("vs_eq_va");
        t.Actions.Count.Should().Be(11);
        t.Actions[0].Verb.Should().Be("F := P");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Set Version 2.2");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("UA");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be("Clear Exception Conditions");
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be("DL-ERROR Indication (F)");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be("Stop T1");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("Start T3");
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be("V(a) := 0");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be("V(s) := 0");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be("V(r) := 0");
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be("RC := 0");
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t15_sabme_received_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t15_sabme_received_no");
        t.On.Should().Be("SABME_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not vs_eq_va");
        t.Actions.Count.Should().Be(13);
        t.Actions[0].Verb.Should().Be("F := P");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Set Version 2.2");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("UA");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be("Clear Exception Conditions");
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be("DL-ERROR Indication (F)");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("DL-CONNECT Indication");
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be("Stop T1");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be("Start T3");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be("V(a) := 0");
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be("V(s) := 0");
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
        t.Actions[11].Verb.Should().Be("V(r) := 0");
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
        t.Actions[12].Verb.Should().Be("RC := 0");
        t.Actions[12].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t16_frmr_received_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t16_frmr_received_no");
        t.On.Should().Be("FRMR_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (K)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Clear Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t16_frmr_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t16_frmr_received_yes");
        t.On.Should().Be("FRMR_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (K)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Clear Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t17_ua_received_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t17_ua_received_no");
        t.On.Should().Be("UA_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (K)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Clear Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t17_ua_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t17_ua_received_yes");
        t.On.Should().Be("UA_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (K)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Clear Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t18_ui_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t18_ui_received_yes");
        t.On.Should().Be("UI_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("P_eq_1");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be("UI Check");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Enquiry_Response_F_1");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t18_ui_received_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t18_ui_received_no");
        t.On.Should().Be("UI_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not P_eq_1");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("UI Check");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t19_disc_received()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t19_disc_received");
        t.On.Should().Be("DISC_received");
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("F := P");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("UA");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be("DL-DISCONNECT Indication");
        t.Actions[3].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[4].Verb.Should().Be("Stop T3");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("Start T1");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t20_dm_received()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t20_dm_received");
        t.On.Should().Be("DM_received");
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (E)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("DL-DISCONNECT Indication");
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be("discard_I_frame_queue");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Stop T1");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Stop T3");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t21_rr_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t21_rr_received_yes");
        t.On.Should().Be("RR_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("va_le_nr_le_vs");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Check I Frame Acknowledged");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t21_rr_received_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t21_rr_received_no_no");
        t.On.Should().Be("RR_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not va_le_nr_le_vs and not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t21_rr_received_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t21_rr_received_no_yes");
        t.On.Should().Be("RR_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("not va_le_nr_le_vs and version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t22_rnr_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t22_rnr_received_yes");
        t.On.Should().Be("RNR_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("va_le_nr_le_vs");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("set_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Check I Frame Acknowledged");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t22_rnr_received_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t22_rnr_received_no_no");
        t.On.Should().Be("RNR_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not va_le_nr_le_vs and not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("set_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t22_rnr_received_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t22_rnr_received_no_yes");
        t.On.Should().Be("RNR_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("not va_le_nr_le_vs and version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("set_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_lm_seize_confirm_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t23_lm_seize_confirm_yes");
        t.On.Should().Be("LM_SEIZE_confirm");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("ack_pending");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Enquiry Response (F = 0)");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("LM-RELEASE Request");
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t23_lm_seize_confirm_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t23_lm_seize_confirm_no");
        t.On.Should().Be("LM_SEIZE_confirm");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not ack_pending");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("LM-RELEASE Request");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t24_srej_received_yes_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t24_srej_received_yes_yes");
        t.On.Should().Be("SREJ_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("va_le_nr_le_vs and P_or_F_eq_1");
        t.Actions.Count.Should().Be(11);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("V(a) := N(r)");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Stop T1");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Start T3");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("Select_T1_Value");
        t.Actions[5].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[6].Verb.Should().Be("Push Old I Frame N(r) on Queue");
        t.Actions[6].Kind.Should().Be(ActionKind.InternalOut);
        t.Actions[7].Verb.Should().Be("LM-DATA Request");
        t.Actions[7].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[8].Verb.Should().Be("Stop T3");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be("Start T1");
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_yes_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t24_srej_received_yes_no");
        t.On.Should().Be("SREJ_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("va_le_nr_le_vs and not P_or_F_eq_1");
        t.Actions.Count.Should().Be(10);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Stop T1");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Start T3");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Select_T1_Value");
        t.Actions[4].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[5].Verb.Should().Be("Push Old I Frame N(r) on Queue");
        t.Actions[5].Kind.Should().Be(ActionKind.InternalOut);
        t.Actions[6].Verb.Should().Be("LM-DATA Request");
        t.Actions[6].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[7].Verb.Should().Be("Stop T3");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be("Start T1");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t24_srej_received_no_no");
        t.On.Should().Be("SREJ_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not va_le_nr_le_vs and not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t24_srej_received_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t24_srej_received_no_yes");
        t.On.Should().Be("SREJ_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("not va_le_nr_le_vs and version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t25_rej_received_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t25_rej_received_no_no");
        t.On.Should().Be("REJ_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("not va_le_nr_le_vs and not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t25_rej_received_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t25_rej_received_no_yes");
        t.On.Should().Be("REJ_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("not va_le_nr_le_vs and version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t25_rej_received_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t25_rej_received_yes");
        t.On.Should().Be("REJ_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("va_le_nr_le_vs");
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be("clear_peer_receiver_busy");
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be("Check Need For Response");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("V(a) := N(r)");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Start T1");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Stop T3");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("Select_T1_Value");
        t.Actions[6].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[7].Verb.Should().Be("Invoke Retransmission");
        t.Actions[7].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t26_i_received_yes_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_no_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("command and not info_field_length_le_N1_and_content_is_octet_aligned and not version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (O)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Clear Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_no_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("command and not info_field_length_le_N1_and_content_is_octet_aligned and version_2_2");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (O)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Establish_Data_Link");
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be("Clear Layer 3 Initiated");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_no_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and not va_le_nr_le_vs and not version_2_2");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t26_i_received_yes_yes_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_no_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and not va_le_nr_le_vs and version_2_2");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be("N(r) Error Recovery");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_yes_no_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_yes_no_no_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and not P_eq_1 and not ack_pending");
        t.Actions.Count.Should().Be(7);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("V(r) := V(r) + 1");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Clear Reject Exception");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Decrement Sreject Exception if > 0");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("DL-DATA Indication");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be("LM-SEIZE Request");
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[6].Verb.Should().Be("set_acknowledge_pending");
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_yes_no_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_yes_no_no_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and not P_eq_1 and ack_pending");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("V(r) := V(r) + 1");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Clear Reject Exception");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Decrement Sreject Exception if > 0");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("DL-DATA Indication");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_yes_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_yes_no_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and P_eq_1");
        t.Actions.Count.Should().Be(9);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("V(r) := V(r) + 1");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Clear Reject Exception");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Decrement Sreject Exception if > 0");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("DL-DATA Indication");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be("F := 1");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("N(r) := V(r)");
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be("RR");
        t.Actions[7].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[8].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_no_yes_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_no_yes_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and reject_exception and P_eq_1");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Discard Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("F := 1");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("N(r) := V(r)");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("RR");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_no_yes_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_no_yes_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and reject_exception and not P_eq_1");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Discard Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_no_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_no_no_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and not reject_exception and not SREJ_enabled");
        t.Actions.Count.Should().Be(7);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Discard Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Set Reject Exception");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("F := P");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("N(r) := V(r)");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("REJ");
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[6].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_no_no_yes_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_no_no_yes_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and not reject_exception and SREJ_enabled and sreject_exception_gt_0");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Save Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("N(r) := N(s)");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("F := 0");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Increment Sreject Exception");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("SREJ");
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_no_no_yes_no_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_no_no_yes_no_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and not reject_exception and SREJ_enabled and not sreject_exception_gt_0 and ns_gt_vr_plus_1");
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Save Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("Discard Contents of I Frame");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("Set Reject Exception");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("F := P");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("N(r) := V(r)");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be("REJ");
        t.Actions[6].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[7].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_no_no_no_yes_no_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_no_no_no_yes_no_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and not reject_exception and SREJ_enabled and not sreject_exception_gt_0 and not ns_gt_vr_plus_1");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Save Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("N(r) := V(r)");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("F := 1");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("Increment Sreject Exception");
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be("SREJ");
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t26_i_received_yes_yes_yes_yes_yes()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_yes_yes");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and own_receiver_busy and P_eq_1");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Discard Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be("F := 1");
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be("N(r) := V(r)");
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be("RR");
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be("Clear Acknowledge Pending");
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_yes_yes_yes_yes_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_yes_yes_yes_yes_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and own_receiver_busy and not P_eq_1");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be("Check_I_Frame_Acknowledged");
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be("Discard Contents of I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t26_i_received_no()
    {
        var t = DataLink_Connected.Transitions.Single(x => x.Id == "t26_i_received_no");
        t.On.Should().Be("I_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Be("not command");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be("DL-ERROR Indication (O)");
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be("Discard I Frame");
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

}
