// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Linq;
using AwesomeAssertions;
using Packet.Ax25.Sdl;
using Xunit;

namespace Packet.Ax25.Conformance.Tests;

public class DataLink_Disconnected_GeneratedTests
{
    [Fact] public void SourceFigure() => DataLink_Disconnected.Source.Figure.Should().Be("figc4.1");

    [Fact] public void TransitionsArePresent() => DataLink_Disconnected.Transitions.Count.Should().Be(17);

    [Fact] public void t01_dl_disconnect_request()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t01_dl_disconnect_request");
        t.On.Should().Be(Ax25Event.DLDISCONNECTRequest);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTConfirm);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t02_dl_unit_data_request()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t02_dl_unit_data_request");
        t.On.Should().Be(Ax25Event.DLUNITDATARequest);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICommand);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t03_dl_connect_request()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t03_dl_connect_request");
        t.On.Should().Be(Ax25Event.DLCONNECTRequest);
        t.Next.Should().Be("AwaitingConnection");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SRTAssignInitialDefault);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.T1VAssign2TimesSRT);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t04_all_other_primitives__from_upper_layer()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t04_all_other_primitives__from_upper_layer");
        t.On.Should().Be(Ax25Event.AllOtherPrimitivesFromUpperLayer);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t05_all_other_commands()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t05_all_other_commands");
        t.On.Should().Be(Ax25Event.AllOtherCommands);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t06_all_other_primitives__from_lower_layer()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t06_all_other_primitives__from_lower_layer");
        t.On.Should().Be(Ax25Event.AllOtherPrimitivesFromLowerLayer);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardPrimitive);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t07_control_field_error()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t07_control_field_error");
        t.On.Should().Be(Ax25Event.ControlFieldError);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationL);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t08_info_not_permitted_in_frame()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t08_info_not_permitted_in_frame");
        t.On.Should().Be(Ax25Event.InfoNotPermittedInFrame);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationM);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t09_u_or_s_frame_length_error()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t09_u_or_s_frame_length_error");
        t.On.Should().Be(Ax25Event.UOrSFrameLengthError);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationN);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t10_ua_received()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t10_ua_received");
        t.On.Should().Be(Ax25Event.UAReceived);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationCD);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t11_ui_received_no()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t11_ui_received_no");
        t.On.Should().Be(Ax25Event.UIReceived);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t11_ui_received_yes()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t11_ui_received_yes");
        t.On.Should().Be(Ax25Event.UIReceived);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.FAssign1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DM);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t12_disc_received()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t12_disc_received");
        t.On.Should().Be(Ax25Event.DISCReceived);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t13_sabm_received_no()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t13_sabm_received_no");
        t.On.Should().Be(Ax25Event.SABMReceived);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.AbleToEstablish, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t13_sabm_received_yes()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t13_sabm_received_yes");
        t.On.Should().Be(Ax25Event.SABMReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.AbleToEstablish, false) });
        t.Actions.Count.Should().Be(12);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion20);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearExceptionConditions);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.DLCONNECTIndication);
        t.Actions[7].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.SRTAssignInitialDefault);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.T1VAssign2TimesSRT);
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
        t.Actions[11].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t14_sabme_received_no()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t14_sabme_received_no");
        t.On.Should().Be(Ax25Event.SABMEReceived);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.AbleToEstablish, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t14_sabme_received_yes()
    {
        var t = DataLink_Disconnected.Transitions.Single(x => x.Id == "t14_sabme_received_yes");
        t.On.Should().Be(Ax25Event.SABMEReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.AbleToEstablish, false) });
        t.Actions.Count.Should().Be(12);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion22);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearExceptionConditions);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.DLCONNECTIndication);
        t.Actions[7].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.SRTAssignInitialDefault);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.T1VAssign2TimesSRT);
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
        t.Actions[11].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
    }

}
