// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Linq;
using AwesomeAssertions;
using Packet.Ax25.Sdl;
using Xunit;

namespace Packet.Ax25.Conformance.Tests;

public class DataLink_AwaitingRelease_GeneratedTests
{
    [Fact] public void SourceFigure() => DataLink_AwaitingRelease.Source.Figure.Should().Be("figc4.3");

    [Fact] public void TransitionsArePresent() => DataLink_AwaitingRelease.Transitions.Count.Should().Be(20);

    [Fact] public void t01_dl_disconnect_request()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t01_dl_disconnect_request");
        t.On.Should().Be(Ax25Event.DLDISCONNECTRequest);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ExpeditedDM);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t02_t1_expiry_yes()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t02_t1_expiry_yes");
        t.On.Should().Be(Ax25Event.T1Expiry);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationG);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t02_t1_expiry_no()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t02_t1_expiry_no");
        t.On.Should().Be(Ax25Event.T1Expiry);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.RCAssignRCPlus1);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DISCPEq1);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t03_ua_received_yes()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t03_ua_received_yes");
        t.On.Should().Be(Ax25Event.UAReceived);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTConfirm);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t03_ua_received_no()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t03_ua_received_no");
        t.On.Should().Be(Ax25Event.UAReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationD);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t04_all_other_primitives__from_lower_layer()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t04_all_other_primitives__from_lower_layer");
        t.On.Should().Be(Ax25Event.AllOtherPrimitivesFromLowerLayer);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t05_dl_unit_data_request()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t05_dl_unit_data_request");
        t.On.Should().Be(Ax25Event.DLUNITDATARequest);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICommand);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t06_all_other_primitives__from_upper_layer()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t06_all_other_primitives__from_upper_layer");
        t.On.Should().Be(Ax25Event.AllOtherPrimitivesFromUpperLayer);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t07_control_field_error()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t07_control_field_error");
        t.On.Should().Be(Ax25Event.ControlFieldError);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationL);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t08_info_not_permitted_in_frame()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t08_info_not_permitted_in_frame");
        t.On.Should().Be(Ax25Event.InfoNotPermittedInFrame);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationM);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t09_u_or_s_frame_length_error()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t09_u_or_s_frame_length_error");
        t.On.Should().Be(Ax25Event.UOrSFrameLengthError);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationN);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t10_sabm_received()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t10_sabm_received");
        t.On.Should().Be(Ax25Event.SABMReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.ExpeditedDM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t11_sabme_received()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t11_sabme_received");
        t.On.Should().Be(Ax25Event.SABMEReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.ExpeditedDM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t12_disc_received()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t12_disc_received");
        t.On.Should().Be(Ax25Event.DISCReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.ExpeditedUA);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t13_dm_received_yes()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t13_dm_received_yes");
        t.On.Should().Be(Ax25Event.DMReceived);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTConfirm);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t13_dm_received_no()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t13_dm_received_no");
        t.On.Should().Be(Ax25Event.DMReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, true) });
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t14_ui_received_yes()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t14_ui_received_yes");
        t.On.Should().Be(Ax25Event.UIReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DMFEq1);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t14_ui_received_no()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t14_ui_received_no");
        t.On.Should().Be(Ax25Event.UIReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t15_i_or_s_command_received_yes()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t15_i_or_s_command_received_yes");
        t.On.Should().Be(Ax25Event.IOrSCommandReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DMFEq1);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t15_i_or_s_command_received_no()
    {
        var t = DataLink_AwaitingRelease.Transitions.Single(x => x.Id == "t15_i_or_s_command_received_no");
        t.On.Should().Be(Ax25Event.IOrSCommandReceived);
        t.Next.Should().Be("AwaitingRelease");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(0);
    }

}
