// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Linq;
using AwesomeAssertions;
using Packet.Ax25.Sdl;
using Xunit;

namespace Packet.Ax25.Conformance.Tests;

public class DataLink_AwaitingV22Connection_GeneratedTests
{
    [Fact] public void SourceFigure() => DataLink_AwaitingV22Connection.Source.Figure.Should().Be("figc4.6");

    [Fact] public void TransitionsArePresent() => DataLink_AwaitingV22Connection.Transitions.Count.Should().Be(25);

    [Fact] public void t02_dl_connect_request()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t02_dl_connect_request");
        t.On.Should().Be("DL_CONNECT_request");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t03_dl_unit_data_request()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t03_dl_unit_data_request");
        t.On.Should().Be("DL_UNIT_DATA_request");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICommand);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t04_dl_data_request_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t04_dl_data_request_yes");
        t.On.Should().Be("DL_DATA_request");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Layer3Initiated, false) });
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t04_dl_data_request_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t04_dl_data_request_no");
        t.On.Should().Be("DL_DATA_request");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Layer3Initiated, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.PushFrameOnQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t05_i_frame_pops_off_queue_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t05_i_frame_pops_off_queue_yes");
        t.On.Should().Be("I_frame_pops_off_queue");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Layer3Initiated, false) });
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t05_i_frame_pops_off_queue_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t05_i_frame_pops_off_queue_no");
        t.On.Should().Be("I_frame_pops_off_queue");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Layer3Initiated, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.PushFrameOnQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t06_all_other_primitives__from_upper_layer()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t06_all_other_primitives__from_upper_layer");
        t.On.Should().Be("all_other_primitives__from_upper_layer");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t07_control_field_error()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t07_control_field_error");
        t.On.Should().Be("control_field_error");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationL);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t08_info_not_permitted_in_frame()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t08_info_not_permitted_in_frame");
        t.On.Should().Be("info_not_permitted_in_frame");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationM);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t09_u_or_s_frame_length_error()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t09_u_or_s_frame_length_error");
        t.On.Should().Be("u_or_s_frame_length_error");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationN);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t10_ui_received_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t10_ui_received_no");
        t.On.Should().Be("UI_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DMFEq1);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t10_ui_received_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t10_ui_received_yes");
        t.On.Should().Be("UI_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t11_dm_received_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t11_dm_received_no");
        t.On.Should().Be("DM_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, true) });
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t11_dm_received_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t11_dm_received_yes");
        t.On.Should().Be("DM_received");
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t12_ua_received_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t12_ua_received_no");
        t.On.Should().Be("UA_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationD);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t12_ua_received_yes_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t12_ua_received_yes_yes");
        t.On.Should().Be("UA_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, false), new GuardTerm(Ax25Guard.Layer3Initiated, false) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLCONNECTConfirm);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[6].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.MDLNEGOTIATERequest);
        t.Actions[7].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t12_ua_received_yes_no_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t12_ua_received_yes_no_no");
        t.On.Should().Be("UA_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, false), new GuardTerm(Ax25Guard.Layer3Initiated, true), new GuardTerm(Ax25Guard.VsEqVa, true) });
        t.Actions.Count.Should().Be(11);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SRTAssignInitialDefault);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.T1VAssign2TimesSRT);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DLCONNECTConfirm);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[9].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[10].Verb.Should().Be(Ax25ActionVerb.MDLNEGOTIATERequest);
        t.Actions[10].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t12_ua_received_yes_no_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t12_ua_received_yes_no_yes");
        t.On.Should().Be("UA_received");
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.FEq1, false), new GuardTerm(Ax25Guard.Layer3Initiated, true), new GuardTerm(Ax25Guard.VsEqVa, false) });
        t.Actions.Count.Should().Be(7);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[5].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.MDLNEGOTIATERequest);
        t.Actions[6].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t13_t1_expiry_yes()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t13_t1_expiry_yes");
        t.On.Should().Be("T1_expiry");
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardFrameQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationG);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t13_t1_expiry_no()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t13_t1_expiry_no");
        t.On.Should().Be("T1_expiry");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.RCAssignRCPlus1);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SABMEPEq1);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t14_frmr_received()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t14_frmr_received");
        t.On.Should().Be("FRMR_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SRTAssignInitialDefault);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.T1VAssign2TimesSRT);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.SetVersion20);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t15_sabme_received()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t15_sabme_received");
        t.On.Should().Be("SABME_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t16_sabm_received()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t16_sabm_received");
        t.On.Should().Be("SABM_received");
        t.Next.Should().Be("AwaitingConnection");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SetVersion20);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t17_disc_received()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t17_disc_received");
        t.On.Should().Be("DISC_received");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DM);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t18_all_other_primitives__from_lower_layer()
    {
        var t = DataLink_AwaitingV22Connection.Transitions.Single(x => x.Id == "t18_all_other_primitives__from_lower_layer");
        t.On.Should().Be("all_other_primitives__from_lower_layer");
        t.Next.Should().Be("AwaitingV22Connection");
        t.Actions.Count.Should().Be(0);
    }

}
