// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Linq;
using AwesomeAssertions;
using Packet.Ax25.Sdl;
using Xunit;

namespace Packet.Ax25.Conformance.Tests;

public class ManagementDataLink_Ready_GeneratedTests
{
    [Fact] public void SourceFigure() => ManagementDataLink_Ready.Source.Figure.Should().Be("figc5.1");

    [Fact] public void TransitionsArePresent() => ManagementDataLink_Ready.Transitions.Count.Should().Be(2);

    [Fact] public void t01_mdl_negotiate_request()
    {
        var t = ManagementDataLink_Ready.Transitions.Single(x => x.Id == "t01_mdl_negotiate_request");
        t.On.Should().Be("MDL_NEGOTIATE_request");
        t.Next.Should().Be("Negotiating");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.XIDCommand);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.StartTM201);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t02_xid_response_received()
    {
        var t = ManagementDataLink_Ready.Transitions.Single(x => x.Id == "t02_xid_response_received");
        t.On.Should().Be("XID_response_received");
        t.Next.Should().Be("Ready");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.MDLERRORIndicateB);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
    }

}
