// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/management-data-link/yaml/negotiating.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

import { describe, it, expect } from "vitest";
import { ManagementDataLinkNegotiating } from "./negotiating.g.js";

describe("ManagementDataLinkNegotiating", () => {
  it("source figure", () => {
    expect(ManagementDataLinkNegotiating.source.figure).toBe("figc5.2");
  });

  it("transitions are present", () => {
    expect(ManagementDataLinkNegotiating.transitions).toHaveLength(5);
  });

  it("t01_xid_response_received_yes", () => {
    const t = ManagementDataLinkNegotiating.transitions.find((x) => x.id === "t01_xid_response_received_yes");
    expect(t, "transition t01_xid_response_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("XID_response_received");
    expect(t.next).toBe("Ready");
    expect(t.guard).toEqual([{ atom: "F_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("Apply Negotiated Parameters");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Stop TM201");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("MDL_NEGOTIATE_confirm");
    expect(t.actions[2].kind).toBe("signal_upper");
  });

  it("t01_xid_response_received_no", () => {
    const t = ManagementDataLinkNegotiating.transitions.find((x) => x.id === "t01_xid_response_received_no");
    expect(t, "transition t01_xid_response_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("XID_response_received");
    expect(t.next).toBe("Negotiating");
    expect(t.guard).toEqual([{ atom: "F_eq_1", negate: true }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("MDL_ERROR_indicate_D");
    expect(t.actions[0].kind).toBe("signal_upper");
  });

  it("t02_frmr_received", () => {
    const t = ManagementDataLinkNegotiating.transitions.find((x) => x.id === "t02_frmr_received");
    expect(t, "transition t02_frmr_received not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("FRMR_received");
    expect(t.next).toBe("Ready");
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("set_version_2_0");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Stop TM201");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("MDL_NEGOTIATE_confirm");
    expect(t.actions[2].kind).toBe("signal_upper");
  });

  it("t03_tm201_expiry_yes", () => {
    const t = ManagementDataLinkNegotiating.transitions.find((x) => x.id === "t03_tm201_expiry_yes");
    expect(t, "transition t03_tm201_expiry_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("TM201_expiry");
    expect(t.next).toBe("Ready");
    expect(t.guard).toEqual([{ atom: "RC_eq_NM201", negate: false }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("MDL_ERROR_indicate_C");
    expect(t.actions[0].kind).toBe("signal_upper");
  });

  it("t03_tm201_expiry_no", () => {
    const t = ManagementDataLinkNegotiating.transitions.find((x) => x.id === "t03_tm201_expiry_no");
    expect(t, "transition t03_tm201_expiry_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("TM201_expiry");
    expect(t.next).toBe("Negotiating");
    expect(t.guard).toEqual([{ atom: "RC_eq_NM201", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("RC := RC + 1");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("XID_command");
    expect(t.actions[1].kind).toBe("signal_lower");
    expect(t.actions[2].verb).toBe("Start TM201");
    expect(t.actions[2].kind).toBe("processing");
  });

});
