// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/subroutines.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

import type { SubroutinesPage } from "./types.js";

/**
 * SDL subroutines for the data_link machine.
 * Source: ax.25.2.2.4_Oct_25, figure figc4.7.
 */
export const DataLinkSubroutines: SubroutinesPage = {
  machine: "data_link",
  source: { spec: "ax.25.2.2.4_Oct_25", figure: "figc4.7", url: "" },
  subroutines: [
    {
      name: "Set_Version_2_2",
      paths: [
        {
          id: "t01_set_version_2_2",
          guard: [],
          actions: [
            { verb: "Set Half Duplex", kind: "processing" },
            { verb: "Set Selective Reject", kind: "processing" },
            { verb: "Modulo := 128", kind: "processing" },
            { verb: "N1 := 2048", kind: "processing" },
            { verb: "k := 32", kind: "processing" },
            { verb: "T2 := 3000", kind: "processing" },
            { verb: "N2 := 10", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "UI_Check",
      paths: [
        {
          id: "t01_ui_check_no",
          guard: [{ atom: "command", negate: true }],
          actions: [
            { verb: "DL-ERROR Indication (Q)", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_ui_check_yes_yes",
          guard: [{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }],
          actions: [
            { verb: "DL_UNIT_DATA_indication", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_ui_check_yes_no",
          guard: [{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: true }],
          actions: [
            { verb: "DL-ERROR Indication (K)", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Select_T1",
      paths: [
        {
          id: "t01_select_t1_yes",
          guard: [{ atom: "RC_eq_0", negate: false }],
          actions: [
            { verb: "SRT := 7(SRT)/8 + (T1)/8 - (Remaining Time on T1 When Last Stopped)/8", kind: "processing" },
            { verb: "Next T1 := 2 * SRT", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_select_t1_no_no",
          guard: [{ atom: "RC_eq_0", negate: true }, { atom: "T1_expired", negate: true }],
          actions: [],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_select_t1_no_yes",
          guard: [{ atom: "RC_eq_0", negate: true }, { atom: "T1_expired", negate: false }],
          actions: [
            { verb: "Next T1 := (RC*0.25)+SRT*2", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Set_Version_2_0",
      paths: [
        {
          id: "t01_set_version_2_0",
          guard: [],
          actions: [
            { verb: "Set Half Duplex", kind: "processing" },
            { verb: "Set Implicit Reject", kind: "processing" },
            { verb: "Modulo := 8", kind: "processing" },
            { verb: "N1 := 2048", kind: "processing" },
            { verb: "k := 8", kind: "processing" },
            { verb: "T2 := 3000", kind: "processing" },
            { verb: "N2 := 10", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Check_Need_for_Response",
      paths: [
        {
          id: "t01_check_need_for_response_yes",
          guard: [{ atom: "command_and_P_eq_1", negate: false }],
          actions: [
            { verb: "Enquiry_Response_F_1", kind: "subroutine" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_check_need_for_response_no_no",
          guard: [{ atom: "command_and_P_eq_1", negate: true }, { atom: "response_and_F_eq_1", negate: true }],
          actions: [],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_check_need_for_response_no_yes",
          guard: [{ atom: "command_and_P_eq_1", negate: true }, { atom: "response_and_F_eq_1", negate: false }],
          actions: [
            { verb: "DL-ERROR Indication (A)", kind: "signal_upper" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Establish_Extended_Data_Link",
      paths: [
        {
          id: "t01_establish_extended_data_link_no",
          guard: [{ atom: "mod_128", negate: true }],
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC := 1", kind: "processing" },
            { verb: "P := 1", kind: "processing" },
            { verb: "SABM", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_establish_extended_data_link_yes",
          guard: [{ atom: "mod_128", negate: false }],
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC := 1", kind: "processing" },
            { verb: "P := 1", kind: "processing" },
            { verb: "SABME", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Establish_Data_Link",
      paths: [
        {
          id: "t01_establish_data_link_no",
          guard: [{ atom: "mod_128", negate: true }],
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC := 1", kind: "processing" },
            { verb: "P := 1", kind: "processing" },
            { verb: "SABM", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_establish_data_link_yes",
          guard: [{ atom: "mod_128", negate: false }],
          actions: [
            { verb: "Clear Exception Conditions", kind: "processing" },
            { verb: "RC := 1", kind: "processing" },
            { verb: "P := 1", kind: "processing" },
            { verb: "SABME", kind: "signal_lower" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Invoke_Retransmission",
      paths: [
        {
          id: "t01_invoke_retransmission",
          guard: [],
          actions: [
            { verb: "Backtrack", kind: "processing" },
            { verb: "X := V(s)", kind: "processing" },
            { verb: "V(s) := N(r)", kind: "processing" },
            { verb: "Push Old I Frame onto Queue", kind: "internal_out" },
            { verb: "V(s) := V(s) + 1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [
            { start: 3, length: 2, predicate: { atom: "vs_eq_X", negate: true }, testAtEnd: true },
          ],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Check_I_Frame_Acknowledged",
      paths: [
        {
          id: "t01_check_i_frame_acknowledged_yes_yes",
          guard: [{ atom: "peer_receiver_busy", negate: false }, { atom: "T1_running", negate: false }],
          actions: [
            { verb: "V(a) := N(r)", kind: "processing" },
            { verb: "Stop T3", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_check_i_frame_acknowledged_yes_no",
          guard: [{ atom: "peer_receiver_busy", negate: false }, { atom: "T1_running", negate: true }],
          actions: [
            { verb: "V(a) := N(r)", kind: "processing" },
            { verb: "Stop T3", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_check_i_frame_acknowledged_no_yes",
          guard: [{ atom: "peer_receiver_busy", negate: true }, { atom: "nr_eq_vs", negate: false }],
          actions: [
            { verb: "V(a) := N(r)", kind: "processing" },
            { verb: "Stop T1", kind: "processing" },
            { verb: "Start T3", kind: "processing" },
            { verb: "Select_T1_Value", kind: "subroutine" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t04_check_i_frame_acknowledged_no_no_yes",
          guard: [{ atom: "peer_receiver_busy", negate: true }, { atom: "nr_eq_vs", negate: true }, { atom: "nr_eq_va", negate: false }],
          actions: [],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t05_check_i_frame_acknowledged_no_no_no",
          guard: [{ atom: "peer_receiver_busy", negate: true }, { atom: "nr_eq_vs", negate: true }, { atom: "nr_eq_va", negate: true }],
          actions: [
            { verb: "V(a) := N(r)", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Clear_Exception_Conditions",
      paths: [
        {
          id: "t01_clear_exception_conditions",
          guard: [],
          actions: [
            { verb: "clear_peer_receiver_busy", kind: "processing" },
            { verb: "Clear Own Receiver Busy", kind: "processing" },
            { verb: "Clear Reject Condition", kind: "processing" },
            { verb: "Clear Sreject Condition", kind: "processing" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
            { verb: "Discard I Queue Entries", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "N_r_Error_Recovery",
      paths: [
        {
          id: "t01_n_r_error_recovery",
          guard: [],
          actions: [
            { verb: "DL-ERROR Indication (J)", kind: "signal_upper" },
            { verb: "Establish_Data_Link", kind: "subroutine" },
            { verb: "Clear Layer 3 Initiated", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Transmit_Enquiry",
      paths: [
        {
          id: "t01_transmit_enquiry_no",
          guard: [{ atom: "own_receiver_busy", negate: true }],
          actions: [
            { verb: "P := 1", kind: "processing" },
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "RR Command", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_transmit_enquiry_yes",
          guard: [{ atom: "own_receiver_busy", negate: false }],
          actions: [
            { verb: "P := 1", kind: "processing" },
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "RNR Command", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
            { verb: "Start T1", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
    {
      name: "Enquiry_Response",
      paths: [
        {
          id: "t01_enquiry_response_yes_yes",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: false }, { atom: "own_receiver_busy", negate: false }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "RNR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t02_enquiry_response_yes_no_yes_yes_yes",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "mod_8", negate: false }, { atom: "out_of_sequence_frames_in_receive_buffer", negate: false }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "DL-ERROR Indication (add)", kind: "signal_upper" },
            { verb: "SREJ", kind: "signal_lower" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t03_enquiry_response_yes_no_yes_yes_no",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "mod_8", negate: false }, { atom: "out_of_sequence_frames_in_receive_buffer", negate: true }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "DL-ERROR Indication (add)", kind: "signal_upper" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t04_enquiry_response_yes_no_yes_no_yes",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "mod_8", negate: true }, { atom: "out_of_sequence_frames_in_receive_buffer", negate: false }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "SREJ", kind: "signal_lower" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t05_enquiry_response_yes_no_yes_no_no",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "mod_8", negate: true }, { atom: "out_of_sequence_frames_in_receive_buffer", negate: true }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t06_enquiry_response_yes_no_no",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "SREJ_enabled", negate: true }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
        {
          id: "t07_enquiry_response_no",
          guard: [{ atom: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I", negate: true }],
          actions: [
            { verb: "N(r) := V(r)", kind: "processing" },
            { verb: "RR Response", kind: "signal_lower" },
            { verb: "Clear Acknowledge Pending", kind: "processing" },
          ],
          notes: "",
          references: [],
          loops: [],
        },
      ],
      notes: "",
      references: [],
    },
  ],
};
