// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/disconnected.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

use crate::types::*;

/// SDL transitions for the Disconnected state of the data_link machine.
/// Source: ax.25.2.2.4_Oct_25, figure figc4.1.
pub static DATA_LINK_DISCONNECTED: StatePage = StatePage {
    machine: "data_link",
    state: "Disconnected",
    source: SdlSource {
        spec: "ax.25.2.2.4_Oct_25",
        figure: "figc4.1",
        url: "",
    },
    transitions: &[
        TransitionSpec {
            id: "t01_dl_disconnect_request",
            from: "Disconnected",
            on: "DL_DISCONNECT_request",
            guard: "",
            actions: &[ActionStep {
                verb: "DL-DISCONNECT Confirm",
                kind: ActionKind::SignalUpper,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t02_dl_unit_data_request",
            from: "Disconnected",
            on: "DL_UNIT_DATA_request",
            guard: "",
            actions: &[ActionStep {
                verb: "UI Command",
                kind: ActionKind::SignalLower,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t03_dl_connect_request",
            from: "Disconnected",
            on: "DL_CONNECT_request",
            guard: "",
            actions: &[
                ActionStep {
                    verb: "SRT := Initial Default",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "T1V := 2 * SRT",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "Establish_Data_Link",
                    kind: ActionKind::Subroutine,
                },
                ActionStep {
                    verb: "Set Layer 3 Initiated",
                    kind: ActionKind::Processing,
                },
            ],
            next: "AwaitingConnection",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t04_all_other_primitives__from_lower_layer",
            from: "Disconnected",
            on: "all_other_primitives__from_lower_layer",
            guard: "",
            actions: &[],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t05_all_other_commands",
            from: "Disconnected",
            on: "all_other_commands",
            guard: "",
            actions: &[
                ActionStep {
                    verb: "F := P",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DM",
                    kind: ActionKind::SignalLower,
                },
            ],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t06_all_other_primitives__from_upper_layer",
            from: "Disconnected",
            on: "all_other_primitives__from_upper_layer",
            guard: "",
            actions: &[ActionStep {
                verb: "Discard Primitive",
                kind: ActionKind::Processing,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t07_control_field_error",
            from: "Disconnected",
            on: "control_field_error",
            guard: "",
            actions: &[ActionStep {
                verb: "DL-ERROR Indication (L)",
                kind: ActionKind::SignalUpper,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t08_info_not_permitted_in_frame",
            from: "Disconnected",
            on: "info_not_permitted_in_frame",
            guard: "",
            actions: &[ActionStep {
                verb: "DL-ERROR Indication (M)",
                kind: ActionKind::SignalUpper,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t09_u_or_s_frame_length_error",
            from: "Disconnected",
            on: "u_or_s_frame_length_error",
            guard: "",
            actions: &[ActionStep {
                verb: "DL-ERROR Indication (N)",
                kind: ActionKind::SignalUpper,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t10_ua_received",
            from: "Disconnected",
            on: "UA_received",
            guard: "",
            actions: &[ActionStep {
                verb: "DL-ERROR Indication (C,D)",
                kind: ActionKind::SignalUpper,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t11_ui_received_no",
            from: "Disconnected",
            on: "UI_received",
            guard: "not P_eq_1",
            actions: &[ActionStep {
                verb: "UI Check",
                kind: ActionKind::Subroutine,
            }],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t11_ui_received_yes",
            from: "Disconnected",
            on: "UI_received",
            guard: "P_eq_1",
            actions: &[
                ActionStep {
                    verb: "UI Check",
                    kind: ActionKind::Subroutine,
                },
                ActionStep {
                    verb: "F := 1",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DM",
                    kind: ActionKind::SignalLower,
                },
            ],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t12_disc_received",
            from: "Disconnected",
            on: "DISC_received",
            guard: "",
            actions: &[
                ActionStep {
                    verb: "F := P",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DM",
                    kind: ActionKind::SignalLower,
                },
            ],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t13_sabm_received_no",
            from: "Disconnected",
            on: "SABM_received",
            guard: "not able_to_establish",
            actions: &[
                ActionStep {
                    verb: "F := P",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DM",
                    kind: ActionKind::SignalLower,
                },
            ],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t13_sabm_received_yes",
            from: "Disconnected",
            on: "SABM_received",
            guard: "able_to_establish",
            actions: &[
                ActionStep {
                    verb: "F := P",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "set_version_2_0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "UA",
                    kind: ActionKind::SignalLower,
                },
                ActionStep {
                    verb: "Clear Exception Conditions",
                    kind: ActionKind::Subroutine,
                },
                ActionStep {
                    verb: "V(s) := 0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "V(a) := 0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "V(r) := 0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DL Connect Indication",
                    kind: ActionKind::SignalUpper,
                },
                ActionStep {
                    verb: "SRT := Initial Default",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "T1V := 2 * SRT",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "Start T3",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "RC := 0",
                    kind: ActionKind::Processing,
                },
            ],
            next: "Connected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t14_sabme_received_no",
            from: "Disconnected",
            on: "SABME_received",
            guard: "not able_to_establish",
            actions: &[
                ActionStep {
                    verb: "F := P",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DM",
                    kind: ActionKind::SignalLower,
                },
            ],
            next: "Disconnected",
            notes: "",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t14_sabme_received_yes",
            from: "Disconnected",
            on: "SABME_received",
            guard: "able_to_establish",
            actions: &[
                ActionStep {
                    verb: "F := P",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "Set Version 2.2",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "UA",
                    kind: ActionKind::SignalLower,
                },
                ActionStep {
                    verb: "Clear Exception Conditions",
                    kind: ActionKind::Subroutine,
                },
                ActionStep {
                    verb: "V(s) := 0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "V(a) := 0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "V(r) := 0",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "DL Connect Indication",
                    kind: ActionKind::SignalUpper,
                },
                ActionStep {
                    verb: "SRT := Initial Default",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "T1V := 2 * SRT",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "Start T3",
                    kind: ActionKind::Processing,
                },
                ActionStep {
                    verb: "RC := 0",
                    kind: ActionKind::Processing,
                },
            ],
            next: "Connected",
            notes: "",
            references: &[],
            loops: &[],
        },
    ],
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn source_figure() {
        assert_eq!(DATA_LINK_DISCONNECTED.source.figure, "figc4.1");
    }

    #[test]
    fn transitions_are_present() {
        assert_eq!(DATA_LINK_DISCONNECTED.transitions.len(), 17);
    }

    #[test]
    fn t01_dl_disconnect_request() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t01_dl_disconnect_request")
            .expect("transition t01_dl_disconnect_request not found");
        assert_eq!(tx.on, "DL_DISCONNECT_request");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL-DISCONNECT Confirm");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t02_dl_unit_data_request() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t02_dl_unit_data_request")
            .expect("transition t02_dl_unit_data_request not found");
        assert_eq!(tx.on, "DL_UNIT_DATA_request");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "UI Command");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t03_dl_connect_request() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t03_dl_connect_request")
            .expect("transition t03_dl_connect_request not found");
        assert_eq!(tx.on, "DL_CONNECT_request");
        assert_eq!(tx.next, "AwaitingConnection");
        assert_eq!(tx.actions.len(), 4);
        assert_eq!(tx.actions[0].verb, "SRT := Initial Default");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "T1V := 2 * SRT");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "Establish_Data_Link");
        assert_eq!(tx.actions[2].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[3].verb, "Set Layer 3 Initiated");
        assert_eq!(tx.actions[3].kind, ActionKind::Processing);
    }

    #[test]
    fn t04_all_other_primitives__from_lower_layer() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t04_all_other_primitives__from_lower_layer")
            .expect("transition t04_all_other_primitives__from_lower_layer not found");
        assert_eq!(tx.on, "all_other_primitives__from_lower_layer");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 0);
    }

    #[test]
    fn t05_all_other_commands() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t05_all_other_commands")
            .expect("transition t05_all_other_commands not found");
        assert_eq!(tx.on, "all_other_commands");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DM");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t06_all_other_primitives__from_upper_layer() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t06_all_other_primitives__from_upper_layer")
            .expect("transition t06_all_other_primitives__from_upper_layer not found");
        assert_eq!(tx.on, "all_other_primitives__from_upper_layer");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "Discard Primitive");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
    }

    #[test]
    fn t07_control_field_error() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t07_control_field_error")
            .expect("transition t07_control_field_error not found");
        assert_eq!(tx.on, "control_field_error");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL-ERROR Indication (L)");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t08_info_not_permitted_in_frame() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t08_info_not_permitted_in_frame")
            .expect("transition t08_info_not_permitted_in_frame not found");
        assert_eq!(tx.on, "info_not_permitted_in_frame");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL-ERROR Indication (M)");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t09_u_or_s_frame_length_error() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t09_u_or_s_frame_length_error")
            .expect("transition t09_u_or_s_frame_length_error not found");
        assert_eq!(tx.on, "u_or_s_frame_length_error");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL-ERROR Indication (N)");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t10_ua_received() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t10_ua_received")
            .expect("transition t10_ua_received not found");
        assert_eq!(tx.on, "UA_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL-ERROR Indication (C,D)");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t11_ui_received_no() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t11_ui_received_no")
            .expect("transition t11_ui_received_no not found");
        assert_eq!(tx.on, "UI_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.guard, "not P_eq_1");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "UI Check");
        assert_eq!(tx.actions[0].kind, ActionKind::Subroutine);
    }

    #[test]
    fn t11_ui_received_yes() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t11_ui_received_yes")
            .expect("transition t11_ui_received_yes not found");
        assert_eq!(tx.on, "UI_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.guard, "P_eq_1");
        assert_eq!(tx.actions.len(), 3);
        assert_eq!(tx.actions[0].verb, "UI Check");
        assert_eq!(tx.actions[0].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[1].verb, "F := 1");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "DM");
        assert_eq!(tx.actions[2].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t12_disc_received() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t12_disc_received")
            .expect("transition t12_disc_received not found");
        assert_eq!(tx.on, "DISC_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DM");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t13_sabm_received_no() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t13_sabm_received_no")
            .expect("transition t13_sabm_received_no not found");
        assert_eq!(tx.on, "SABM_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.guard, "not able_to_establish");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DM");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t13_sabm_received_yes() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t13_sabm_received_yes")
            .expect("transition t13_sabm_received_yes not found");
        assert_eq!(tx.on, "SABM_received");
        assert_eq!(tx.next, "Connected");
        assert_eq!(tx.guard, "able_to_establish");
        assert_eq!(tx.actions.len(), 12);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "set_version_2_0");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "UA");
        assert_eq!(tx.actions[2].kind, ActionKind::SignalLower);
        assert_eq!(tx.actions[3].verb, "Clear Exception Conditions");
        assert_eq!(tx.actions[3].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[4].verb, "V(s) := 0");
        assert_eq!(tx.actions[4].kind, ActionKind::Processing);
        assert_eq!(tx.actions[5].verb, "V(a) := 0");
        assert_eq!(tx.actions[5].kind, ActionKind::Processing);
        assert_eq!(tx.actions[6].verb, "V(r) := 0");
        assert_eq!(tx.actions[6].kind, ActionKind::Processing);
        assert_eq!(tx.actions[7].verb, "DL Connect Indication");
        assert_eq!(tx.actions[7].kind, ActionKind::SignalUpper);
        assert_eq!(tx.actions[8].verb, "SRT := Initial Default");
        assert_eq!(tx.actions[8].kind, ActionKind::Processing);
        assert_eq!(tx.actions[9].verb, "T1V := 2 * SRT");
        assert_eq!(tx.actions[9].kind, ActionKind::Processing);
        assert_eq!(tx.actions[10].verb, "Start T3");
        assert_eq!(tx.actions[10].kind, ActionKind::Processing);
        assert_eq!(tx.actions[11].verb, "RC := 0");
        assert_eq!(tx.actions[11].kind, ActionKind::Processing);
    }

    #[test]
    fn t14_sabme_received_no() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t14_sabme_received_no")
            .expect("transition t14_sabme_received_no not found");
        assert_eq!(tx.on, "SABME_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.guard, "not able_to_establish");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DM");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t14_sabme_received_yes() {
        let tx = DATA_LINK_DISCONNECTED
            .transitions
            .iter()
            .find(|x| x.id == "t14_sabme_received_yes")
            .expect("transition t14_sabme_received_yes not found");
        assert_eq!(tx.on, "SABME_received");
        assert_eq!(tx.next, "Connected");
        assert_eq!(tx.guard, "able_to_establish");
        assert_eq!(tx.actions.len(), 12);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "Set Version 2.2");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "UA");
        assert_eq!(tx.actions[2].kind, ActionKind::SignalLower);
        assert_eq!(tx.actions[3].verb, "Clear Exception Conditions");
        assert_eq!(tx.actions[3].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[4].verb, "V(s) := 0");
        assert_eq!(tx.actions[4].kind, ActionKind::Processing);
        assert_eq!(tx.actions[5].verb, "V(a) := 0");
        assert_eq!(tx.actions[5].kind, ActionKind::Processing);
        assert_eq!(tx.actions[6].verb, "V(r) := 0");
        assert_eq!(tx.actions[6].kind, ActionKind::Processing);
        assert_eq!(tx.actions[7].verb, "DL Connect Indication");
        assert_eq!(tx.actions[7].kind, ActionKind::SignalUpper);
        assert_eq!(tx.actions[8].verb, "SRT := Initial Default");
        assert_eq!(tx.actions[8].kind, ActionKind::Processing);
        assert_eq!(tx.actions[9].verb, "T1V := 2 * SRT");
        assert_eq!(tx.actions[9].kind, ActionKind::Processing);
        assert_eq!(tx.actions[10].verb, "Start T3");
        assert_eq!(tx.actions[10].kind, ActionKind::Processing);
        assert_eq!(tx.actions[11].verb, "RC := 0");
        assert_eq!(tx.actions[11].kind, ActionKind::Processing);
    }
}
