// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/management-data-link/yaml/ready.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

use crate::types::*;

/// SDL transitions for the Ready state of the management_data_link machine.
/// Source: ax.25.2.2.4_Oct_25, figure figc5.1.
pub static MANAGEMENT_DATA_LINK_READY: StatePage = StatePage {
    machine: "management_data_link",
    state: "Ready",
    source: SdlSource {
        spec: "ax.25.2.2.4_Oct_25",
        figure: "figc5.1",
        url: "https://raw.githubusercontent.com/packethacking/ax25spec/main/doc/ax.25.2.2.4_Oct_25.md",
    },
    transitions: &[
        TransitionSpec {
            id: "t01_mdl_negotiate_request",
            from: "Ready",
            on: Ax25Event::MDLNEGOTIATERequest,
            guard: &[],
            actions: &[
                ActionStep { verb: Ax25ActionVerb::RCAssign0, kind: ActionKind::Processing },
                ActionStep { verb: Ax25ActionVerb::XIDCommand, kind: ActionKind::SignalLower },
                ActionStep { verb: Ax25ActionVerb::StartTM201, kind: ActionKind::Processing },
            ],
            next: "Negotiating",
            notes: "verification_pending (prose-derived bootstrap; figc5.1 graphml redraw pending — see backfill task). Derived from Appendix C5.3 ¶3 (\"The station initiating the AX.25 connection will send an XID command after it receives the UA frame\") + C5.3 Variables/Timers (RC, NM201, TM201). The ORDER of the three steps (RC:=0, send XID, start TM201) and the XID command's P=1 bit are NOT stated by the prose — error A (\"XID command without P=1\", C5.3 Error Codes) implies the command carries P=1, but the exact action ordering and the P-bit assignment box are figc5.1 detail and unverified. The DL→MDL handoff that raises this input is the data-link figc4.6 (AwaitingV22Connection) UA-received path, which emits `MDL-NEGOTIATE Request` (internal_out) on a successful v2.2 connect — see spec-sdl/.../data-link/yaml/awaiting_v22_connection.sdl.yaml.",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§C5.3 ¶3", quote: "The station initiating the AX.25 connection will send an XID command after it receives the UA frame.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "spec_prose", cite: "§6.3.2 ¶1", quote: "Parameter negotiation occurs only before the connection is made. It is accomplished by sending the XID command frame and receiving the XID response frame.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "spec_prose", cite: "§5.1", quote: "MDL-NEGOTIATE Request. The Layer 3 entity uses this primitive to request the Data-link State Machine to notify/negotiate.", path: "", function: "", line: 0, note: "" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t02_xid_response_received",
            from: "Ready",
            on: Ax25Event::XIDResponseReceived,
            guard: &[],
            actions: &[
                ActionStep { verb: Ax25ActionVerb::MDLERRORIndicateB, kind: ActionKind::SignalUpper },
            ],
            next: "Ready",
            notes: "verification_pending (prose-derived bootstrap; figc5.1 graphml redraw pending — see backfill task). The EXISTENCE of error B (\"Unexpected XID response\", §C5.3 Error Codes) is prose-clear, and Ready is the defensible state for it (no XID command outstanding). But the figc5.1 column for a received XID response — whether it is drawn at all in Ready, what (if any) frame is emitted, and the precise MDL-ERROR letter wiring — is unverified figure detail. Encoded as the most defensible reading of the error-code list, NOT from a figure.",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§C5.3 Error Codes", quote: "B — Unexpected XID response.", path: "", function: "", line: 0, note: "" },
            ],
            loops: &[],
        },
    ],
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn source_figure() {
        assert_eq!(MANAGEMENT_DATA_LINK_READY.source.figure, "figc5.1");
    }

    #[test]
    fn transitions_are_present() {
        assert_eq!(MANAGEMENT_DATA_LINK_READY.transitions.len(), 2);
    }

    #[test]
    fn t01_mdl_negotiate_request() {
        let tx = MANAGEMENT_DATA_LINK_READY
            .transitions
            .iter()
            .find(|x| x.id == "t01_mdl_negotiate_request")
            .expect("transition t01_mdl_negotiate_request not found");
        assert_eq!(tx.on, Ax25Event::MDLNEGOTIATERequest);
        assert_eq!(tx.next, "Negotiating");
        assert_eq!(tx.actions.len(), 3);
        assert_eq!(tx.actions[0].verb, Ax25ActionVerb::RCAssign0);
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, Ax25ActionVerb::XIDCommand);
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
        assert_eq!(tx.actions[2].verb, Ax25ActionVerb::StartTM201);
        assert_eq!(tx.actions[2].kind, ActionKind::Processing);
    }

    #[test]
    fn t02_xid_response_received() {
        let tx = MANAGEMENT_DATA_LINK_READY
            .transitions
            .iter()
            .find(|x| x.id == "t02_xid_response_received")
            .expect("transition t02_xid_response_received not found");
        assert_eq!(tx.on, Ax25Event::XIDResponseReceived);
        assert_eq!(tx.next, "Ready");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, Ax25ActionVerb::MDLERRORIndicateB);
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }
}
