// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/subroutines.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

use crate::types::*;

/// SDL subroutines for the data_link machine.
/// Source: ax.25.2.2.4_Oct_25, figure figc4.7.
pub static DATA_LINK_SUBROUTINES: SubroutinesPage = SubroutinesPage {
    machine: "data_link",
    source: SdlSource {
        spec: "ax.25.2.2.4_Oct_25",
        figure: "figc4.7",
        url: "",
    },
    subroutines: &[
        SubroutineSpec {
            name: "Set_Version_2_2",
            paths: &[
                SubroutinePath {
                    id: "t01_set_version_2_2",
                    guard: &[],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::SetHalfDuplex, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SetSelectiveReject, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::ModuloAssign128, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::N1Assign2048, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::KAssign32, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::T2Assign3000, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::N2Assign10, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "UI_Check",
            paths: &[
                SubroutinePath {
                    id: "t01_ui_check_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Command, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::DLERRORIndicationQ, kind: ActionKind::SignalUpper },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_ui_check_yes_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Command, negate: false },
                        GuardTerm { atom: Ax25Guard::InfoFieldLengthLeN1AndContentIsOctetAligned, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::DLUNITDATAIndication, kind: ActionKind::SignalUpper },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t03_ui_check_yes_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Command, negate: false },
                        GuardTerm { atom: Ax25Guard::InfoFieldLengthLeN1AndContentIsOctetAligned, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::DLERRORIndicationK, kind: ActionKind::SignalUpper },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Select_T1",
            paths: &[
                SubroutinePath {
                    id: "t01_select_t1_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::RCEq0, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::SRTAssign7SRT8PlusT18RemainingTimeOnT1WhenLastStopped8, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::NextT1Assign2TimesSRT, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_select_t1_no_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::RCEq0, negate: true },
                        GuardTerm { atom: Ax25Guard::T1Expired, negate: true },
                    ],
                    actions: &[],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t03_select_t1_no_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::RCEq0, negate: true },
                        GuardTerm { atom: Ax25Guard::T1Expired, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NextT1AssignRCTimes025PlusSRTTimes2, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Set_Version_2_0",
            paths: &[
                SubroutinePath {
                    id: "t01_set_version_2_0",
                    guard: &[],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::SetHalfDuplex, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SetImplicitReject, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::ModuloAssign8, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::N1Assign2048, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::KAssign8, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::T2Assign3000, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::N2Assign10, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Check_Need_for_Response",
            paths: &[
                SubroutinePath {
                    id: "t01_check_need_for_response_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::CommandAndPEq1, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::EnquiryResponseF1, kind: ActionKind::Subroutine },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_check_need_for_response_no_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::CommandAndPEq1, negate: true },
                        GuardTerm { atom: Ax25Guard::ResponseAndFEq1, negate: true },
                    ],
                    actions: &[],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t03_check_need_for_response_no_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::CommandAndPEq1, negate: true },
                        GuardTerm { atom: Ax25Guard::ResponseAndFEq1, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::DLERRORIndicationA, kind: ActionKind::SignalUpper },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Establish_Extended_Data_Link",
            paths: &[
                SubroutinePath {
                    id: "t01_establish_extended_data_link_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Mod128, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::ClearExceptionConditions, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RCAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::PAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SABM, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::StopT3, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_establish_extended_data_link_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Mod128, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::ClearExceptionConditions, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RCAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::PAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SABME, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::StopT3, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Establish_Data_Link",
            paths: &[
                SubroutinePath {
                    id: "t01_establish_data_link_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Mod128, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::ClearExceptionConditions, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RCAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::PAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SABM, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::StopT3, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_establish_data_link_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::Mod128, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::ClearExceptionConditions, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RCAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::PAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SABME, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::StopT3, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Invoke_Retransmission",
            paths: &[
                SubroutinePath {
                    id: "t01_invoke_retransmission",
                    guard: &[],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::Backtrack, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::XAssignVS, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::VSAssignNR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::PushOldIFrameOntoQueue, kind: ActionKind::InternalOut },
                        ActionStep { verb: Ax25ActionVerb::VSAssignVSPlus1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[
                        LoopRange { start: 3, length: 2, predicate: GuardTerm { atom: Ax25Guard::VsEqX, negate: true }, test_at_end: true },
                    ],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Check_I_Frame_Acknowledged",
            paths: &[
                SubroutinePath {
                    id: "t01_check_i_frame_acknowledged_yes_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::PeerReceiverBusy, negate: false },
                        GuardTerm { atom: Ax25Guard::T1Running, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::VAAssignNR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StopT3, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_check_i_frame_acknowledged_yes_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::PeerReceiverBusy, negate: false },
                        GuardTerm { atom: Ax25Guard::T1Running, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::VAAssignNR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StopT3, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t03_check_i_frame_acknowledged_no_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::PeerReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::NrEqVs, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::VAAssignNR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StopT1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT3, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SelectT1Value, kind: ActionKind::Subroutine },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t04_check_i_frame_acknowledged_no_no_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::PeerReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::NrEqVs, negate: true },
                        GuardTerm { atom: Ax25Guard::NrEqVa, negate: false },
                    ],
                    actions: &[],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t05_check_i_frame_acknowledged_no_no_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::PeerReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::NrEqVs, negate: true },
                        GuardTerm { atom: Ax25Guard::NrEqVa, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::VAAssignNR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Clear_Exception_Conditions",
            paths: &[
                SubroutinePath {
                    id: "t01_clear_exception_conditions",
                    guard: &[],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::ClearPeerReceiverBusy, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::ClearOwnReceiverBusy, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::ClearRejectCondition, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::ClearSrejectCondition, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::DiscardIQueueEntries, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "N_r_Error_Recovery",
            paths: &[
                SubroutinePath {
                    id: "t01_n_r_error_recovery",
                    guard: &[],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::DLERRORIndicationJ, kind: ActionKind::SignalUpper },
                        ActionStep { verb: Ax25ActionVerb::EstablishDataLink, kind: ActionKind::Subroutine },
                        ActionStep { verb: Ax25ActionVerb::ClearLayer3Initiated, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Transmit_Enquiry",
            paths: &[
                SubroutinePath {
                    id: "t01_transmit_enquiry_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::PAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RRCommand, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_transmit_enquiry_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::PAssign1, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RNRCommand, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::StartT1, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
        SubroutineSpec {
            name: "Enquiry_Response",
            paths: &[
                SubroutinePath {
                    id: "t01_enquiry_response_yes_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: false },
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RNRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t02_enquiry_response_yes_no_yes_yes_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: false },
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::SREJEnabled, negate: false },
                        GuardTerm { atom: Ax25Guard::Mod8, negate: false },
                        GuardTerm { atom: Ax25Guard::OutOfSequenceFramesInReceiveBuffer, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::DLERRORIndicationAdd, kind: ActionKind::SignalUpper },
                        ActionStep { verb: Ax25ActionVerb::SREJ, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::RRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t03_enquiry_response_yes_no_yes_yes_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: false },
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::SREJEnabled, negate: false },
                        GuardTerm { atom: Ax25Guard::Mod8, negate: false },
                        GuardTerm { atom: Ax25Guard::OutOfSequenceFramesInReceiveBuffer, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::DLERRORIndicationAdd, kind: ActionKind::SignalUpper },
                        ActionStep { verb: Ax25ActionVerb::RRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t04_enquiry_response_yes_no_yes_no_yes",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: false },
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::SREJEnabled, negate: false },
                        GuardTerm { atom: Ax25Guard::Mod8, negate: true },
                        GuardTerm { atom: Ax25Guard::OutOfSequenceFramesInReceiveBuffer, negate: false },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::SREJ, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::RRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t05_enquiry_response_yes_no_yes_no_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: false },
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::SREJEnabled, negate: false },
                        GuardTerm { atom: Ax25Guard::Mod8, negate: true },
                        GuardTerm { atom: Ax25Guard::OutOfSequenceFramesInReceiveBuffer, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t06_enquiry_response_yes_no_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: false },
                        GuardTerm { atom: Ax25Guard::OwnReceiverBusy, negate: true },
                        GuardTerm { atom: Ax25Guard::SREJEnabled, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
                SubroutinePath {
                    id: "t07_enquiry_response_no",
                    guard: &[
                        GuardTerm { atom: Ax25Guard::FEq1AndFrameEqRROrFrameEqRNROrFrameEqI, negate: true },
                    ],
                    actions: &[
                        ActionStep { verb: Ax25ActionVerb::NRAssignVR, kind: ActionKind::Processing },
                        ActionStep { verb: Ax25ActionVerb::RRResponse, kind: ActionKind::SignalLower },
                        ActionStep { verb: Ax25ActionVerb::ClearAcknowledgePending, kind: ActionKind::Processing },
                    ],
                    notes: "",
                    references: &[],
                    loops: &[],
                },
            ],
            notes: "",
            references: &[],
        },
    ],
};
