// Code generated by codegen/src/Packet.Sdl.CodeGen from
// spec-sdl/v2.2-errata/management-data-link/yaml/negotiating.sdl.yaml. DO NOT
// EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to
// regenerate.

#include "ax25sdl.h"
#include <stdio.h>
#include <string.h>

extern const StatePage management_data_link_negotiating;

#define ASSERT(cond, msg)                                                      \
  do {                                                                         \
    if (!(cond)) {                                                             \
      fprintf(stderr, "FAIL: %s\n", msg);                                      \
      return 1;                                                                \
    }                                                                          \
  } while (0)
#define ASSERT_STREQ(a, b, msg) ASSERT(strcmp((a), (b)) == 0, msg)

static int test_source_figure(void) {
  ASSERT_STREQ(management_data_link_negotiating.source.figure, "figc5.2",
               "source.figure");
  return 0;
}

static int test_transitions_count(void) {
  ASSERT(management_data_link_negotiating.transitions_len == 5,
         "transitions count");
  return 0;
}

static int test_t01_xid_response_received_yes(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_negotiating.transitions_len;
       i++) {
    if (strcmp(management_data_link_negotiating.transitions[i].id,
               "t01_xid_response_received_yes") == 0) {
      t = &management_data_link_negotiating.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t01_xid_response_received_yes not found");
  ASSERT_STREQ(t->on, "XID_response_received", "on");
  ASSERT_STREQ(t->next, "Ready", "next");
  ASSERT_STREQ(t->guard, "F_eq_1", "guard");
  ASSERT(t->actions_len == 3, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "Apply Negotiated Parameters",
               "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SUBROUTINE, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "Stop TM201", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_PROCESSING, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "MDL_NEGOTIATE_confirm", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[2].kind");
  return 0;
}

static int test_t01_xid_response_received_no(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_negotiating.transitions_len;
       i++) {
    if (strcmp(management_data_link_negotiating.transitions[i].id,
               "t01_xid_response_received_no") == 0) {
      t = &management_data_link_negotiating.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t01_xid_response_received_no not found");
  ASSERT_STREQ(t->on, "XID_response_received", "on");
  ASSERT_STREQ(t->next, "Negotiating", "next");
  ASSERT_STREQ(t->guard, "not F_eq_1", "guard");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "MDL_ERROR_indicate_D", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t02_frmr_received(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_negotiating.transitions_len;
       i++) {
    if (strcmp(management_data_link_negotiating.transitions[i].id,
               "t02_frmr_received") == 0) {
      t = &management_data_link_negotiating.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t02_frmr_received not found");
  ASSERT_STREQ(t->on, "FRMR_received", "on");
  ASSERT_STREQ(t->next, "Ready", "next");
  ASSERT(t->actions_len == 3, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "set_version_2_0", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "Stop TM201", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_PROCESSING, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "MDL_NEGOTIATE_confirm", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[2].kind");
  return 0;
}

static int test_t03_tm201_expiry_yes(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_negotiating.transitions_len;
       i++) {
    if (strcmp(management_data_link_negotiating.transitions[i].id,
               "t03_tm201_expiry_yes") == 0) {
      t = &management_data_link_negotiating.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t03_tm201_expiry_yes not found");
  ASSERT_STREQ(t->on, "TM201_expiry", "on");
  ASSERT_STREQ(t->next, "Ready", "next");
  ASSERT_STREQ(t->guard, "RC_eq_NM201", "guard");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "MDL_ERROR_indicate_C", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

static int test_t03_tm201_expiry_no(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_negotiating.transitions_len;
       i++) {
    if (strcmp(management_data_link_negotiating.transitions[i].id,
               "t03_tm201_expiry_no") == 0) {
      t = &management_data_link_negotiating.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t03_tm201_expiry_no not found");
  ASSERT_STREQ(t->on, "TM201_expiry", "on");
  ASSERT_STREQ(t->next, "Negotiating", "next");
  ASSERT_STREQ(t->guard, "not RC_eq_NM201", "guard");
  ASSERT(t->actions_len == 3, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "RC := RC + 1", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "XID_command", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "Start TM201", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_PROCESSING, "actions[2].kind");
  return 0;
}

int main(void) {
  int rc = 0;
  rc |= test_source_figure();
  rc |= test_transitions_count();
  rc |= test_t01_xid_response_received_yes();
  rc |= test_t01_xid_response_received_no();
  rc |= test_t02_frmr_received();
  rc |= test_t03_tm201_expiry_yes();
  rc |= test_t03_tm201_expiry_no();
  return rc;
}
