// Code generated by codegen/src/Packet.Sdl.CodeGen from
// spec-sdl/v2.2-errata/management-data-link/yaml/ready.sdl.yaml. DO NOT EDIT.
// Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

#include "ax25sdl.h"
#include <stdio.h>
#include <string.h>

extern const StatePage management_data_link_ready;

#define ASSERT(cond, msg)                                                      \
  do {                                                                         \
    if (!(cond)) {                                                             \
      fprintf(stderr, "FAIL: %s\n", msg);                                      \
      return 1;                                                                \
    }                                                                          \
  } while (0)
#define ASSERT_STREQ(a, b, msg) ASSERT(strcmp((a), (b)) == 0, msg)

static int test_source_figure(void) {
  ASSERT_STREQ(management_data_link_ready.source.figure, "figc5.1",
               "source.figure");
  return 0;
}

static int test_transitions_count(void) {
  ASSERT(management_data_link_ready.transitions_len == 2, "transitions count");
  return 0;
}

static int test_t01_mdl_negotiate_request(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_ready.transitions_len; i++) {
    if (strcmp(management_data_link_ready.transitions[i].id,
               "t01_mdl_negotiate_request") == 0) {
      t = &management_data_link_ready.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t01_mdl_negotiate_request not found");
  ASSERT_STREQ(t->on, "MDL_NEGOTIATE_request", "on");
  ASSERT_STREQ(t->next, "Negotiating", "next");
  ASSERT(t->actions_len == 3, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "RC := 0", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_PROCESSING, "actions[0].kind");
  ASSERT_STREQ(t->actions[1].verb, "XID_command", "actions[1].verb");
  ASSERT(t->actions[1].kind == AX25SDL_KIND_SIGNAL_LOWER, "actions[1].kind");
  ASSERT_STREQ(t->actions[2].verb, "Start TM201", "actions[2].verb");
  ASSERT(t->actions[2].kind == AX25SDL_KIND_PROCESSING, "actions[2].kind");
  return 0;
}

static int test_t02_xid_response_received(void) {
  const TransitionSpec *t = NULL;
  for (size_t i = 0; i < management_data_link_ready.transitions_len; i++) {
    if (strcmp(management_data_link_ready.transitions[i].id,
               "t02_xid_response_received") == 0) {
      t = &management_data_link_ready.transitions[i];
      break;
    }
  }
  ASSERT(t != NULL, "t02_xid_response_received not found");
  ASSERT_STREQ(t->on, "XID_response_received", "on");
  ASSERT_STREQ(t->next, "Ready", "next");
  ASSERT(t->actions_len == 1, "actions count");
  ASSERT_STREQ(t->actions[0].verb, "MDL_ERROR_indicate_B", "actions[0].verb");
  ASSERT(t->actions[0].kind == AX25SDL_KIND_SIGNAL_UPPER, "actions[0].kind");
  return 0;
}

int main(void) {
  int rc = 0;
  rc |= test_source_figure();
  rc |= test_transitions_count();
  rc |= test_t01_mdl_negotiate_request();
  rc |= test_t02_xid_response_received();
  return rc;
}
