# Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/management-data-link/yaml/ready.sdl.yaml.
# DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

from . import MANAGEMENT_DATA_LINK_READY
from .types import ActionKind


def test_source_figure() -> None:
    assert MANAGEMENT_DATA_LINK_READY.source.figure == "figc5.1"


def test_transitions_are_present() -> None:
    assert len(MANAGEMENT_DATA_LINK_READY.transitions) == 2


def test_t01_mdl_negotiate_request() -> None:
    t = next(
        (x for x in MANAGEMENT_DATA_LINK_READY.transitions if x.id == "t01_mdl_negotiate_request"),
        None,
    )
    assert t is not None, "transition t01_mdl_negotiate_request not found"
    assert t.on == "MDL_NEGOTIATE_request"
    assert t.next == "Negotiating"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "RC := 0"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "XID_command"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[2].verb == "Start TM201"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t02_xid_response_received() -> None:
    t = next(
        (x for x in MANAGEMENT_DATA_LINK_READY.transitions if x.id == "t02_xid_response_received"),
        None,
    )
    assert t is not None, "transition t02_xid_response_received not found"
    assert t.on == "XID_response_received"
    assert t.next == "Ready"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "MDL_ERROR_indicate_B"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER

