// <auto-generated />
// Generated by Packet.Sdl.CodeGen — do not edit. See spec-sdl/actions.yaml.
#nullable enable

namespace Packet.Ax25.Sdl;

/// <summary>
/// The closed set of canonical AX.25 SDL action verbs (figc4.x), one member per
/// distinct semantic action across every page + subroutine. Carried by
/// <see cref="ActionStep.Verb"/>; lets a dispatcher switch exhaustively.
/// </summary>
public enum Ax25ActionVerb
{
    /// <summary><c>Apply Negotiated Parameters</c></summary>
    ApplyNegotiatedParameters,
    /// <summary><c>Backtrack</c></summary>
    Backtrack,
    /// <summary><c>Check Need For Response</c></summary>
    CheckNeedForResponse,
    /// <summary><c>Check_I_Frame_Acknowledged</c></summary>
    CheckIFrameAcknowledged,
    /// <summary><c>Clear Acknowledge Pending</c></summary>
    ClearAcknowledgePending,
    /// <summary><c>Clear Exception Conditions</c></summary>
    ClearExceptionConditions,
    /// <summary><c>Clear Layer 3 Initiated</c></summary>
    ClearLayer3Initiated,
    /// <summary><c>Clear Own Receiver Busy</c></summary>
    ClearOwnReceiverBusy,
    /// <summary><c>Clear Reject Condition</c></summary>
    ClearRejectCondition,
    /// <summary><c>Clear Reject Exception</c></summary>
    ClearRejectException,
    /// <summary><c>Clear Sreject Condition</c></summary>
    ClearSrejectCondition,
    /// <summary><c>DISC (P = 1)</c></summary>
    DISCPEq1,
    /// <summary><c>DL-ERROR Indication (A)</c></summary>
    DLERRORIndicationA,
    /// <summary><c>DL-ERROR Indication (E)</c></summary>
    DLERRORIndicationE,
    /// <summary><c>DL-ERROR Indication (F)</c></summary>
    DLERRORIndicationF,
    /// <summary><c>DL-ERROR Indication (G)</c></summary>
    DLERRORIndicationG,
    /// <summary><c>DL-ERROR Indication (I)</c></summary>
    DLERRORIndicationI,
    /// <summary><c>DL-ERROR Indication (J)</c></summary>
    DLERRORIndicationJ,
    /// <summary><c>DL-ERROR Indication (K)</c></summary>
    DLERRORIndicationK,
    /// <summary><c>DL-ERROR Indication (L)</c></summary>
    DLERRORIndicationL,
    /// <summary><c>DL-ERROR Indication (M)</c></summary>
    DLERRORIndicationM,
    /// <summary><c>DL-ERROR Indication (N)</c></summary>
    DLERRORIndicationN,
    /// <summary><c>DL-ERROR Indication (O)</c></summary>
    DLERRORIndicationO,
    /// <summary><c>DL-ERROR Indication (Q)</c></summary>
    DLERRORIndicationQ,
    /// <summary><c>DL-ERROR Indication (T)</c></summary>
    DLERRORIndicationT,
    /// <summary><c>DL-ERROR Indication (U)</c></summary>
    DLERRORIndicationU,
    /// <summary><c>DL-ERROR Indication (add)</c></summary>
    DLERRORIndicationAdd,
    /// <summary><c>DL_CONNECT_confirm</c></summary>
    DLCONNECTConfirm,
    /// <summary><c>DL_CONNECT_indication</c></summary>
    DLCONNECTIndication,
    /// <summary><c>DL_DATA_indication</c></summary>
    DLDATAIndication,
    /// <summary><c>DL_DISCONNECT_confirm</c></summary>
    DLDISCONNECTConfirm,
    /// <summary><c>DL_DISCONNECT_indication</c></summary>
    DLDISCONNECTIndication,
    /// <summary><c>DL_ERROR_indication_C_D</c></summary>
    DLERRORIndicationCD,
    /// <summary><c>DL_ERROR_indication_D</c></summary>
    DLERRORIndicationD,
    /// <summary><c>DL_UNIT_DATA_indication</c></summary>
    DLUNITDATAIndication,
    /// <summary><c>DM</c></summary>
    DM,
    /// <summary><c>DM (F = 1)</c></summary>
    DMFEq1,
    /// <summary><c>DM Response (F = 0)</c></summary>
    DMResponseFEq0,
    /// <summary><c>Decrement Sreject Exception if &gt; 0</c></summary>
    DecrementSrejectExceptionIf0,
    /// <summary><c>Discard Contents of I Frame</c></summary>
    DiscardContentsOfIFrame,
    /// <summary><c>Discard I Frame</c></summary>
    DiscardIFrame,
    /// <summary><c>Discard I Queue Entries</c></summary>
    DiscardIQueueEntries,
    /// <summary><c>Discard Primitive</c></summary>
    DiscardPrimitive,
    /// <summary><c>Discard Queue</c></summary>
    DiscardQueue,
    /// <summary><c>Enquiry Response (F = 0)</c></summary>
    EnquiryResponseFEq0,
    /// <summary><c>Enquiry_Response_F_1</c></summary>
    EnquiryResponseF1,
    /// <summary><c>Establish_Data_Link</c></summary>
    EstablishDataLink,
    /// <summary><c>Expedited DM</c></summary>
    ExpeditedDM,
    /// <summary><c>Expedited UA</c></summary>
    ExpeditedUA,
    /// <summary><c>F := 0</c></summary>
    FAssign0,
    /// <summary><c>F := 1</c></summary>
    FAssign1,
    /// <summary><c>F := P</c></summary>
    FAssignP,
    /// <summary><c>I Command</c></summary>
    ICommand,
    /// <summary><c>Increment Sreject Exception</c></summary>
    IncrementSrejectException,
    /// <summary><c>Invoke Retransmission</c></summary>
    InvokeRetransmission,
    /// <summary><c>LM_data_request</c></summary>
    LMDataRequest,
    /// <summary><c>LM_release_request</c></summary>
    LMReleaseRequest,
    /// <summary><c>LM_seize_request</c></summary>
    LMSeizeRequest,
    /// <summary><c>MDL-NEGOTIATE Request</c></summary>
    MDLNEGOTIATERequest,
    /// <summary><c>MDL_ERROR_indicate_B</c></summary>
    MDLERRORIndicateB,
    /// <summary><c>MDL_ERROR_indicate_C</c></summary>
    MDLERRORIndicateC,
    /// <summary><c>MDL_ERROR_indicate_D</c></summary>
    MDLERRORIndicateD,
    /// <summary><c>MDL_NEGOTIATE_confirm</c></summary>
    MDLNEGOTIATEConfirm,
    /// <summary><c>Modulo := 128</c></summary>
    ModuloAssign128,
    /// <summary><c>Modulo := 8</c></summary>
    ModuloAssign8,
    /// <summary><c>N(r) := N(s)</c></summary>
    NRAssignNS,
    /// <summary><c>N(r) := V(r)</c></summary>
    NRAssignVR,
    /// <summary><c>N(r) Error Recovery</c></summary>
    NRErrorRecovery,
    /// <summary><c>N(r) Recovery</c></summary>
    NRRecovery,
    /// <summary><c>N(s) := V(s)</c></summary>
    NSAssignVS,
    /// <summary><c>N1 := 2048</c></summary>
    N1Assign2048,
    /// <summary><c>N2 := 10</c></summary>
    N2Assign10,
    /// <summary><c>Next T1 := (RC*0.25)+SRT*2</c></summary>
    NextT1AssignRCTimes025PlusSRTTimes2,
    /// <summary><c>Next T1 := 2 * SRT</c></summary>
    NextT1Assign2TimesSRT,
    /// <summary><c>P := 0</c></summary>
    PAssign0,
    /// <summary><c>P := 1</c></summary>
    PAssign1,
    /// <summary><c>Push I Frame on I Queue</c></summary>
    PushIFrameOnIQueue,
    /// <summary><c>Push Old I Frame N(r) on Queue</c></summary>
    PushOldIFrameNROnQueue,
    /// <summary><c>Push Old I Frame onto Queue</c></summary>
    PushOldIFrameOntoQueue,
    /// <summary><c>Push on I Frame Queue</c></summary>
    PushOnIFrameQueue,
    /// <summary><c>Push on I Frame Queue (note: word order?)</c></summary>
    PushOnIFrameQueueNoteWordOrder,
    /// <summary><c>RC := 0</c></summary>
    RCAssign0,
    /// <summary><c>RC := 1</c></summary>
    RCAssign1,
    /// <summary><c>RC := RC + 1</c></summary>
    RCAssignRCPlus1,
    /// <summary><c>REJ</c></summary>
    REJ,
    /// <summary><c>RNR</c></summary>
    RNR,
    /// <summary><c>RNR Command</c></summary>
    RNRCommand,
    /// <summary><c>RNR Response</c></summary>
    RNRResponse,
    /// <summary><c>RNR Response (F = 0)</c></summary>
    RNRResponseFEq0,
    /// <summary><c>RR</c></summary>
    RR,
    /// <summary><c>RR Command</c></summary>
    RRCommand,
    /// <summary><c>RR Command (P = 0)</c></summary>
    RRCommandPEq0,
    /// <summary><c>RR Response</c></summary>
    RRResponse,
    /// <summary><c>Retrieve Stored V(r) I Frame</c></summary>
    RetrieveStoredVRIFrame,
    /// <summary><c>SABM</c></summary>
    SABM,
    /// <summary><c>SABM (P == 1)</c></summary>
    SABMPEqEq1,
    /// <summary><c>SABME</c></summary>
    SABME,
    /// <summary><c>SABME (P = 1)</c></summary>
    SABMEPEq1,
    /// <summary><c>SREJ</c></summary>
    SREJ,
    /// <summary><c>SRT := 7(SRT)/8 + (T1)/8 - (Remaining Time on T1 When Last Stopped)/8</c></summary>
    SRTAssign7SRT8PlusT18RemainingTimeOnT1WhenLastStopped8,
    /// <summary><c>SRT := Initial Default</c></summary>
    SRTAssignInitialDefault,
    /// <summary><c>Save Contents of I Frame</c></summary>
    SaveContentsOfIFrame,
    /// <summary><c>Select_T1_Value</c></summary>
    SelectT1Value,
    /// <summary><c>Set Half Duplex</c></summary>
    SetHalfDuplex,
    /// <summary><c>Set Implicit Reject</c></summary>
    SetImplicitReject,
    /// <summary><c>Set Layer 3 Initiated</c></summary>
    SetLayer3Initiated,
    /// <summary><c>Set Own Receiver Busy</c></summary>
    SetOwnReceiverBusy,
    /// <summary><c>Set Reject Exception</c></summary>
    SetRejectException,
    /// <summary><c>Set Selective Reject</c></summary>
    SetSelectiveReject,
    /// <summary><c>Set Version 2.2</c></summary>
    SetVersion22,
    /// <summary><c>Sreject := Sreject + 1</c></summary>
    SrejectAssignSrejectPlus1,
    /// <summary><c>Start T1</c></summary>
    StartT1,
    /// <summary><c>Start T3</c></summary>
    StartT3,
    /// <summary><c>Start TM201</c></summary>
    StartTM201,
    /// <summary><c>Stop T1</c></summary>
    StopT1,
    /// <summary><c>Stop T3</c></summary>
    StopT3,
    /// <summary><c>Stop TM201</c></summary>
    StopTM201,
    /// <summary><c>T1V := 2 * SRT</c></summary>
    T1VAssign2TimesSRT,
    /// <summary><c>T2 := 3000</c></summary>
    T2Assign3000,
    /// <summary><c>Transmit Enquery</c></summary>
    TransmitEnquery,
    /// <summary><c>Transmit Enquiry</c></summary>
    TransmitEnquiry,
    /// <summary><c>UA</c></summary>
    UA,
    /// <summary><c>UI Check</c></summary>
    UICheck,
    /// <summary><c>UI Command</c></summary>
    UICommand,
    /// <summary><c>V(a) := 0</c></summary>
    VAAssign0,
    /// <summary><c>V(a) := N(r)</c></summary>
    VAAssignNR,
    /// <summary><c>V(r) := 0</c></summary>
    VRAssign0,
    /// <summary><c>V(r) := V(r) + 1</c></summary>
    VRAssignVRPlus1,
    /// <summary><c>V(r) := V(r) - 1</c></summary>
    VRAssignVR1,
    /// <summary><c>V(s) := 0</c></summary>
    VSAssign0,
    /// <summary><c>V(s) := N(r)</c></summary>
    VSAssignNR,
    /// <summary><c>V(s) := V(s) + 1</c></summary>
    VSAssignVSPlus1,
    /// <summary><c>X := V(s)</c></summary>
    XAssignVS,
    /// <summary><c>XID_command</c></summary>
    XIDCommand,
    /// <summary><c>clear_peer_receiver_busy</c></summary>
    ClearPeerReceiverBusy,
    /// <summary><c>discard_I_frame_queue</c></summary>
    DiscardIFrameQueue,
    /// <summary><c>discard_frame_queue</c></summary>
    DiscardFrameQueue,
    /// <summary><c>k := 32</c></summary>
    KAssign32,
    /// <summary><c>k := 8</c></summary>
    KAssign8,
    /// <summary><c>push_frame_on_queue</c></summary>
    PushFrameOnQueue,
    /// <summary><c>set_acknowledge_pending</c></summary>
    SetAcknowledgePending,
    /// <summary><c>set_peer_receiver_busy</c></summary>
    SetPeerReceiverBusy,
    /// <summary><c>set_version_2_0</c></summary>
    SetVersion20,
}
