// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Collections.Generic;

namespace Packet.Ax25.Sdl;

/// <summary>SDL transitions for the <c>Disconnected</c> state of the <c>data_link</c> machine.</summary>
/// <remarks>Source: ax.25.2.2.4_Oct_25 figc4.1.</remarks>
public static class DataLink_Disconnected
{
    public const string Machine = "data_link";
    public const string State = "Disconnected";

    public static SdlSource Source { get; } = new("ax.25.2.2.4_Oct_25", "figc4.1", null);

    public static IReadOnlyList<TransitionSpec> Transitions { get; } = new TransitionSpec[]
    {
        new TransitionSpec(
            Id: "t01_dl_disconnect_request",
            From: "Disconnected",
            On: "DL_DISCONNECT_request",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL-DISCONNECT Confirm", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t02_dl_unit_data_request",
            From: "Disconnected",
            On: "DL_UNIT_DATA_request",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("UI Command", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t03_dl_connect_request",
            From: "Disconnected",
            On: "DL_CONNECT_request",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("SRT := Initial Default", ActionKind.Processing), new ActionStep("T1V := 2 * SRT", ActionKind.Processing), new ActionStep("Establish_Data_Link", ActionKind.Subroutine), new ActionStep("Set Layer 3 Initiated", ActionKind.Processing) },
            Next: "AwaitingConnection",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t04_all_other_primitives__from_lower_layer",
            From: "Disconnected",
            On: "all_other_primitives__from_lower_layer",
            Guard: null,
            Actions: new ActionStep[] {  },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t05_all_other_commands",
            From: "Disconnected",
            On: "all_other_commands",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t06_all_other_primitives__from_upper_layer",
            From: "Disconnected",
            On: "all_other_primitives__from_upper_layer",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("Discard Primitive", ActionKind.Processing) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t07_control_field_error",
            From: "Disconnected",
            On: "control_field_error",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (L)", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t08_info_not_permitted_in_frame",
            From: "Disconnected",
            On: "info_not_permitted_in_frame",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (M)", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t09_u_or_s_frame_length_error",
            From: "Disconnected",
            On: "u_or_s_frame_length_error",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (N)", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t10_ua_received",
            From: "Disconnected",
            On: "UA_received",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (C,D)", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t11_ui_received_no",
            From: "Disconnected",
            On: "UI_received",
            Guard: "not P_eq_1",
            Actions: new ActionStep[] { new ActionStep("UI Check", ActionKind.Subroutine) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t11_ui_received_yes",
            From: "Disconnected",
            On: "UI_received",
            Guard: "P_eq_1",
            Actions: new ActionStep[] { new ActionStep("UI Check", ActionKind.Subroutine), new ActionStep("F := 1", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t12_disc_received",
            From: "Disconnected",
            On: "DISC_received",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t13_sabm_received_no",
            From: "Disconnected",
            On: "SABM_received",
            Guard: "not able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t13_sabm_received_yes",
            From: "Disconnected",
            On: "SABM_received",
            Guard: "able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("set_version_2_0", ActionKind.Processing), new ActionStep("UA", ActionKind.SignalLower), new ActionStep("Clear Exception Conditions", ActionKind.Subroutine), new ActionStep("V(s) := 0", ActionKind.Processing), new ActionStep("V(a) := 0", ActionKind.Processing), new ActionStep("V(r) := 0", ActionKind.Processing), new ActionStep("DL Connect Indication", ActionKind.SignalUpper), new ActionStep("SRT := Initial Default", ActionKind.Processing), new ActionStep("T1V := 2 * SRT", ActionKind.Processing), new ActionStep("Start T3", ActionKind.Processing), new ActionStep("RC := 0", ActionKind.Processing) },
            Next: "Connected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t14_sabme_received_no",
            From: "Disconnected",
            On: "SABME_received",
            Guard: "not able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
        new TransitionSpec(
            Id: "t14_sabme_received_yes",
            From: "Disconnected",
            On: "SABME_received",
            Guard: "able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("Set Version 2.2", ActionKind.Processing), new ActionStep("UA", ActionKind.SignalLower), new ActionStep("Clear Exception Conditions", ActionKind.Subroutine), new ActionStep("V(s) := 0", ActionKind.Processing), new ActionStep("V(a) := 0", ActionKind.Processing), new ActionStep("V(r) := 0", ActionKind.Processing), new ActionStep("DL Connect Indication", ActionKind.SignalUpper), new ActionStep("SRT := Initial Default", ActionKind.Processing), new ActionStep("T1V := 2 * SRT", ActionKind.Processing), new ActionStep("Start T3", ActionKind.Processing), new ActionStep("RC := 0", ActionKind.Processing) },
            Next: "Connected",
            Notes: null,
            References: new ImplementationReference[] {  },
            Loops: new LoopRange[] {  }),
    };
}
