// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Collections.Generic;

namespace Packet.Ax25.Sdl;

/// <summary>SDL subroutines for the <c>data_link</c> machine.</summary>
/// <remarks>Source: ax.25.2.2.4_Oct_25 figc4.7.</remarks>
public static class DataLink_Subroutines
{
    public const string Machine = "data_link";

    public static SdlSource Source { get; } = new("ax.25.2.2.4_Oct_25", "figc4.7", null);

    public static IReadOnlyList<SubroutineSpec> Subroutines { get; } = new SubroutineSpec[]
    {
        new SubroutineSpec(
            Name: "Set_Version_2_2",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_set_version_2_2",
                    Guard: null,
                    Actions: new ActionStep[] { new ActionStep("Set Half Duplex", ActionKind.Processing), new ActionStep("Set Selective Reject", ActionKind.Processing), new ActionStep("Modulo := 128", ActionKind.Processing), new ActionStep("N1 := 2048", ActionKind.Processing), new ActionStep("k := 32", ActionKind.Processing), new ActionStep("T2 := 3000", ActionKind.Processing), new ActionStep("N2 := 10", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "UI_Check",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_ui_check_no",
                    Guard: "not command",
                    Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (Q)", ActionKind.SignalUpper) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_ui_check_yes_yes",
                    Guard: "command and info_field_length_le_N1_and_content_is_octet_aligned",
                    Actions: new ActionStep[] { new ActionStep("DL-UNIT-DATA Indication", ActionKind.SignalUpper) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t03_ui_check_yes_no",
                    Guard: "command and not info_field_length_le_N1_and_content_is_octet_aligned",
                    Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (K)", ActionKind.SignalUpper) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Select_T1",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_select_t1_yes",
                    Guard: "RC_eq_0",
                    Actions: new ActionStep[] { new ActionStep("SRT := 7(SRT)/8 + (T1)/8 - (Remaining Time on T1 When Last Stopped)/8", ActionKind.Processing), new ActionStep("Next T1 := 2 * SRT", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_select_t1_no_no",
                    Guard: "not RC_eq_0 and not T1_expired",
                    Actions: new ActionStep[] {  },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t03_select_t1_no_yes",
                    Guard: "not RC_eq_0 and T1_expired",
                    Actions: new ActionStep[] { new ActionStep("Next T1 := (RC*0.25)+SRT*2", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Set_Version_2_0",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_set_version_2_0",
                    Guard: null,
                    Actions: new ActionStep[] { new ActionStep("Set Half Duplex", ActionKind.Processing), new ActionStep("Set Implicit Reject", ActionKind.Processing), new ActionStep("Modulo := 8", ActionKind.Processing), new ActionStep("N1 := 2048", ActionKind.Processing), new ActionStep("k := 8", ActionKind.Processing), new ActionStep("T2 := 3000", ActionKind.Processing), new ActionStep("N2 := 10", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Check_Need_for_Response",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_check_need_for_response_yes",
                    Guard: "command_and_P_eq_1",
                    Actions: new ActionStep[] { new ActionStep("Enquiry_Response_F_1", ActionKind.Subroutine) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_check_need_for_response_no_no",
                    Guard: "not command_and_P_eq_1 and not response_and_F_eq_1",
                    Actions: new ActionStep[] {  },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t03_check_need_for_response_no_yes",
                    Guard: "not command_and_P_eq_1 and response_and_F_eq_1",
                    Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (A)", ActionKind.SignalUpper) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Establish_Extended_Data_Link",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_establish_extended_data_link_no",
                    Guard: "not mod_128",
                    Actions: new ActionStep[] { new ActionStep("Clear Exception Conditions", ActionKind.Processing), new ActionStep("RC := 1", ActionKind.Processing), new ActionStep("P := 1", ActionKind.Processing), new ActionStep("SABM", ActionKind.SignalLower), new ActionStep("Stop T3", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_establish_extended_data_link_yes",
                    Guard: "mod_128",
                    Actions: new ActionStep[] { new ActionStep("Clear Exception Conditions", ActionKind.Processing), new ActionStep("RC := 1", ActionKind.Processing), new ActionStep("P := 1", ActionKind.Processing), new ActionStep("SABME", ActionKind.SignalLower), new ActionStep("Stop T3", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Establish_Data_Link",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_establish_data_link_no",
                    Guard: "not mod_128",
                    Actions: new ActionStep[] { new ActionStep("Clear Exception Conditions", ActionKind.Processing), new ActionStep("RC := 1", ActionKind.Processing), new ActionStep("P := 1", ActionKind.Processing), new ActionStep("SABM", ActionKind.SignalLower), new ActionStep("Stop T3", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_establish_data_link_yes",
                    Guard: "mod_128",
                    Actions: new ActionStep[] { new ActionStep("Clear Exception Conditions", ActionKind.Processing), new ActionStep("RC := 1", ActionKind.Processing), new ActionStep("P := 1", ActionKind.Processing), new ActionStep("SABME", ActionKind.SignalLower), new ActionStep("Stop T3", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Invoke_Retransmission",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_invoke_retransmission",
                    Guard: null,
                    Actions: new ActionStep[] { new ActionStep("Backtrack", ActionKind.Processing), new ActionStep("X := V(s)", ActionKind.Processing), new ActionStep("V(s) := N(r)", ActionKind.Processing), new ActionStep("Push Old I Frame onto Queue", ActionKind.InternalOut), new ActionStep("V(s) := V(s) + 1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] { new LoopRange(3, 2, "not vs_eq_X", true) }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Check_I_Frame_Acknowledged",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_check_i_frame_acknowledged_yes_yes",
                    Guard: "peer_receiver_busy and T1_running",
                    Actions: new ActionStep[] { new ActionStep("V(a) := N(r)", ActionKind.Processing), new ActionStep("Stop T3", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_check_i_frame_acknowledged_yes_no",
                    Guard: "peer_receiver_busy and not T1_running",
                    Actions: new ActionStep[] { new ActionStep("V(a) := N(r)", ActionKind.Processing), new ActionStep("Stop T3", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t03_check_i_frame_acknowledged_no_yes",
                    Guard: "not peer_receiver_busy and nr_eq_vs",
                    Actions: new ActionStep[] { new ActionStep("V(a) := N(r)", ActionKind.Processing), new ActionStep("Stop T1", ActionKind.Processing), new ActionStep("Start T3", ActionKind.Processing), new ActionStep("Select_T1_Value", ActionKind.Subroutine) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t04_check_i_frame_acknowledged_no_no_yes",
                    Guard: "not peer_receiver_busy and not nr_eq_vs and nr_eq_va",
                    Actions: new ActionStep[] {  },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t05_check_i_frame_acknowledged_no_no_no",
                    Guard: "not peer_receiver_busy and not nr_eq_vs and not nr_eq_va",
                    Actions: new ActionStep[] { new ActionStep("V(a) := N(r)", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Clear_Exception_Conditions",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_clear_exception_conditions",
                    Guard: null,
                    Actions: new ActionStep[] { new ActionStep("Clear Peer Receiver Busy", ActionKind.Processing), new ActionStep("Clear Own Receiver Busy", ActionKind.Processing), new ActionStep("Clear Reject Condition", ActionKind.Processing), new ActionStep("Clear Sreject Condition", ActionKind.Processing), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing), new ActionStep("Discard I Queue Entries", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "N_r_Error_Recovery",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_n_r_error_recovery",
                    Guard: null,
                    Actions: new ActionStep[] { new ActionStep("DL-ERROR Indication (J)", ActionKind.SignalUpper), new ActionStep("Establish_Data_Link", ActionKind.Subroutine), new ActionStep("Clear Layer 3 Initiated", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Transmit_Enquiry",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_transmit_enquiry_no",
                    Guard: "not own_receiver_busy",
                    Actions: new ActionStep[] { new ActionStep("P := 1", ActionKind.Processing), new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("RR Command", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_transmit_enquiry_yes",
                    Guard: "own_receiver_busy",
                    Actions: new ActionStep[] { new ActionStep("P := 1", ActionKind.Processing), new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("RNR Command", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing), new ActionStep("Start T1", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
        new SubroutineSpec(
            Name: "Enquiry_Response",
            Paths: new SubroutinePath[]
            {
                new SubroutinePath(
                    Id: "t01_enquiry_response_yes_yes",
                    Guard: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I and own_receiver_busy",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("RNR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t02_enquiry_response_yes_no_yes_yes_yes",
                    Guard: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I and not own_receiver_busy and SREJ_enabled and mod_8 and out_of_sequence_frames_in_receive_buffer",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("DL-ERROR Indication (add)", ActionKind.SignalUpper), new ActionStep("SREJ", ActionKind.SignalLower), new ActionStep("RR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t03_enquiry_response_yes_no_yes_yes_no",
                    Guard: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I and not own_receiver_busy and SREJ_enabled and mod_8 and not out_of_sequence_frames_in_receive_buffer",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("DL-ERROR Indication (add)", ActionKind.SignalUpper), new ActionStep("RR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t04_enquiry_response_yes_no_yes_no_yes",
                    Guard: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I and not own_receiver_busy and SREJ_enabled and not mod_8 and out_of_sequence_frames_in_receive_buffer",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("SREJ", ActionKind.SignalLower), new ActionStep("RR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t05_enquiry_response_yes_no_yes_no_no",
                    Guard: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I and not own_receiver_busy and SREJ_enabled and not mod_8 and not out_of_sequence_frames_in_receive_buffer",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("RR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t06_enquiry_response_yes_no_no",
                    Guard: "F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I and not own_receiver_busy and not SREJ_enabled",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("RR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
                new SubroutinePath(
                    Id: "t07_enquiry_response_no",
                    Guard: "not F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I",
                    Actions: new ActionStep[] { new ActionStep("N(r) := V(r)", ActionKind.Processing), new ActionStep("RR Response", ActionKind.SignalLower), new ActionStep("Clear Acknowledge Pending", ActionKind.Processing) },
                    Notes: null,
                    References: new ImplementationReference[] {  },
                    Loops: new LoopRange[] {  }),
            },
            Notes: null,
            References: new ImplementationReference[] {  }),
    };
}
