// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Collections.Generic;

namespace Packet.Ax25.Sdl;

/// <summary>SDL transitions for the <c>Negotiating</c> state of the <c>management_data_link</c> machine.</summary>
/// <remarks>Source: ax.25.2.2.4_Oct_25 figc5.2.</remarks>
public static class ManagementDataLink_Negotiating
{
    public const string Machine = "management_data_link";
    public const string State = "Negotiating";

    public static SdlSource Source { get; } = new("ax.25.2.2.4_Oct_25", "figc5.2", "https://raw.githubusercontent.com/packethacking/ax25spec/main/doc/ax.25.2.2.4_Oct_25.md");

    public static IReadOnlyList<TransitionSpec> Transitions { get; } = new TransitionSpec[]
    {
        new TransitionSpec(
            Id: "t01_xid_response_received_yes",
            From: "Negotiating",
            On: "XID_response_received",
            Guard: "F_eq_1",
            Actions: new ActionStep[] { new ActionStep(Ax25ActionVerb.ApplyNegotiatedParameters, ActionKind.Subroutine), new ActionStep(Ax25ActionVerb.StopTM201, ActionKind.Processing), new ActionStep(Ax25ActionVerb.MDLNEGOTIATEConfirm, ActionKind.SignalUpper) },
            Next: "Ready",
            Notes: "verification_pending (prose-derived bootstrap; figc5.2 graphml redraw pending — see backfill task). Derived from §C5.3 ¶3 (\"If the other station is using version 2.2 or better, it will respond with an XID response\") + §6.3.2 (\"Both TNCs set up based on the values used in the XID response\") + the §C5.3 MDL-NEGOTIATE Confirm primitive. The F==1 split is inferred from error code D (\"XID response without F=1\") — the diamond's presence/placement is NOT figure-verified. `Apply Negotiated Parameters` is a placeholder for the figc5.3–figc5.8 per-parameter \"reverts to\" subroutines (Classes of Procedures → half-duplex; Optional Functions → lesser of REJ/SREJ and modulo 8/128; Ack Timer & Retries → greater; N1 & k → notification/min), which are NOT decomposed here. Whether the figure stops T1 (a data-link timer) in addition to TM201 is UNKNOWN: the §C5.3 timer list names only TM201 for this machine, so only TM201 is stopped here; the task brief's mention of \"stop T1/TM201\" is flagged as figc5.2-dependent and unverified.",
            References: new ImplementationReference[] { new ImplementationReference(Source: "spec_prose", Cite: "§C5.3 ¶3", Quote: "If the other station is using version 2.2 or better, it will respond with an XID response.", Path: null, Function: null, Line: null, Note: null), new ImplementationReference(Source: "spec_prose", Cite: "§6.3.2 ¶7", Quote: "The distant TNC chooses to accept the values offered, or other acceptable values, and places these values in the XID response. Both TNCs set up based on the values used in the XID response.", Path: null, Function: null, Line: null, Note: null), new ImplementationReference(Source: "spec_prose", Cite: "§5.1", Quote: "MDL-NEGOTIATE Confirm. The Management Data-link State Machine uses this primitive to notify the Layer 3 entity that notification/negotiation is complete.", Path: null, Function: null, Line: null, Note: null) },
            Loops: new LoopRange[] {  },
            UndefinedBranches: null,
            OnLabel: "XID"),
        new TransitionSpec(
            Id: "t01_xid_response_received_no",
            From: "Negotiating",
            On: "XID_response_received",
            Guard: "not F_eq_1",
            Actions: new ActionStep[] { new ActionStep(Ax25ActionVerb.MDLERRORIndicateD, ActionKind.SignalUpper) },
            Next: "Negotiating",
            Notes: "verification_pending (prose-derived bootstrap; figc5.2 graphml redraw pending — see backfill task). The error-D condition (\"XID response without F=1\", §C5.3 Error Codes) is prose-clear. The destination state after error D (here: stay in Negotiating, TM201 still running) and whether any frame is emitted are NOT figure-verified — this is the most defensible reading of the error-code list.",
            References: new ImplementationReference[] { new ImplementationReference(Source: "spec_prose", Cite: "§C5.3 Error Codes", Quote: "D — XID response without F=1.", Path: null, Function: null, Line: null, Note: null) },
            Loops: new LoopRange[] {  },
            UndefinedBranches: null,
            OnLabel: "XID"),
        new TransitionSpec(
            Id: "t02_frmr_received",
            From: "Negotiating",
            On: "FRMR_received",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep(Ax25ActionVerb.SetVersion20, ActionKind.Processing), new ActionStep(Ax25ActionVerb.StopTM201, ActionKind.Processing), new ActionStep(Ax25ActionVerb.MDLNEGOTIATEConfirm, ActionKind.SignalUpper) },
            Next: "Ready",
            Notes: "verification_pending (prose-derived bootstrap; figc5.2 graphml redraw pending — see backfill task). Derived from §6.3.2 ¶1 (\"Implementations of AX.25 prior to version 2.2 respond to an XID command frame with a FRMR response frame. The TNC receiving the FRMR uses a default set of parameters compatible with previous versions of AX.25 and a version 2.0 connection is made\") and §C5.3 ¶3. `Set Version 2.0` stands in for installing the §6.3.2 version-2.0 default parameter set (half duplex; implicit reject, modulo 8; N1=2048 bits; k=7; T1=3000 ms; retries=10). The exact action set/order (does the figure draw a distinct \"load v2.0 defaults\" box vs reuse the data-link `Set Version 2.0` verb? does it stop TM201 before or after confirming?) is figc5.2 detail and unverified. The `Set Version 2.0` verb is shared with the data-link figc4.6 FRMR path.",
            References: new ImplementationReference[] { new ImplementationReference(Source: "spec_prose", Cite: "§6.3.2 ¶1", Quote: "Implementations of AX.25 prior to version 2.2 respond to an XID command frame with a FRMR response frame. The TNC receiving the FRMR uses a default set of parameters compatible with previous versions of AX.25 and a version 2.0 connection is made.", Path: null, Function: null, Line: null, Note: null), new ImplementationReference(Source: "spec_prose", Cite: "§C5.3 ¶3", Quote: "If the other station is using a version of AX.25 earlier than 2.2, it will respond with an FRMR of the XID command, and the default version 2.0 parameters will be used.", Path: null, Function: null, Line: null, Note: null) },
            Loops: new LoopRange[] {  },
            UndefinedBranches: null,
            OnLabel: "FRMR"),
        new TransitionSpec(
            Id: "t03_tm201_expiry_yes",
            From: "Negotiating",
            On: "TM201_expiry",
            Guard: "RC_eq_NM201",
            Actions: new ActionStep[] { new ActionStep(Ax25ActionVerb.MDLERRORIndicateC, ActionKind.SignalUpper) },
            Next: "Ready",
            Notes: "verification_pending (prose-derived bootstrap; figc5.2 graphml redraw pending — see backfill task). Derived from §C5.3 Error Codes (\"C — Management retry limit exceeded\"), the §C5.3 Variables (RC, NM201) and Timer (TM201). The retry-limit FSM shape (compare RC to the maximum, give up vs retransmit) is the standard AX.25 retransmit pattern drawn for T1/N2 in the data-link figures (figc4.3 t02, figc4.6 t13); it is reconstructed here for the management timer by analogy and is NOT figure-verified for figc5.2. The destination state on give-up (Ready) and the exact RC comparison sense (== vs >=) are unverified figure detail.",
            References: new ImplementationReference[] { new ImplementationReference(Source: "spec_prose", Cite: "§C5.3 Error Codes", Quote: "C — Management retry limit exceeded.", Path: null, Function: null, Line: null, Note: null), new ImplementationReference(Source: "spec_prose", Cite: "§C5.3 Variables", Quote: "RC — Retry count. NM201 — Maximum number of retries of the XID command.", Path: null, Function: null, Line: null, Note: null) },
            Loops: new LoopRange[] {  },
            UndefinedBranches: null,
            OnLabel: "Timer TM201 Expiry"),
        new TransitionSpec(
            Id: "t03_tm201_expiry_no",
            From: "Negotiating",
            On: "TM201_expiry",
            Guard: "not RC_eq_NM201",
            Actions: new ActionStep[] { new ActionStep(Ax25ActionVerb.RCAssignRCPlus1, ActionKind.Processing), new ActionStep(Ax25ActionVerb.XIDCommand, ActionKind.SignalLower), new ActionStep(Ax25ActionVerb.StartTM201, ActionKind.Processing) },
            Next: "Negotiating",
            Notes: "verification_pending (prose-derived bootstrap; figc5.2 graphml redraw pending — see backfill task). Derived from the §C5.3 Variables (RC, NM201) and Timer (TM201) plus the §6.3.1 link-establishment retry analogue (\"If the distant TNC doesn't respond before T1 times out, the originating TNC resends ... and starts T1 running again. The originating TNC tries to establish a connection until it has tried unsuccessfully N2 times\"). The action set/order (RC:=RC+1, resend XID, restart TM201) mirrors the data-link figc4.3/figc4.6 T1-expiry retransmit column; it is reconstructed by analogy and NOT figure-verified for figc5.2. The resent XID command's P-bit is unverified (see Ready t01 note re error A / P=1).",
            References: new ImplementationReference[] { new ImplementationReference(Source: "spec_prose", Cite: "§C5.3 Variables", Quote: "RC — Retry count. NM201 — Maximum number of retries of the XID command.", Path: null, Function: null, Line: null, Note: null), new ImplementationReference(Source: "spec_prose", Cite: "§6.3.1 ¶2", Quote: "If the distant TNC doesn't respond before T1 times out, the originating TNC resends the SABM frame and starts T1 running again. The originating TNC tries to establish a connection until it has tried unsuccessfully N2 times.", Path: null, Function: null, Line: null, Note: null) },
            Loops: new LoopRange[] {  },
            UndefinedBranches: null,
            OnLabel: "Timer TM201 Expiry"),
    };
}
